### ISSUE TITLE
Invited siddhanth as user, he accepted and has access but is not seen as a user on the user management screen

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1020]
<img width="1426" alt="Screenshot 2024-07-18 at 5 08 29 PM" src="https://github.com/user-attachments/assets/bbfc2b81-b041-4108-817c-5e2171a52d93">

**Comment by fatchat** [comment]
he's an "admin"; see https://github.com/DalgoT4D/DDP_backend/issues/467
