### ISSUE TITLE
Delay between clicking sync on connection and the button switching. In the meantime i'm still able to click.

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1021]
NA

**Comment by fatchat** [comment]
duplicate of https://github.com/DalgoT4D/webapp/issues/1005 
@himanshudube97 has your fix been released?

**Comment by himanshudube97** [comment]
Yes. It's released.

**Comment by fatchat** [comment]
oh i see what happened.. the PR was merged but we didn't release to production. i've done it now
