### ISSUE TITLE
Cast form lagging/glitching

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1041]
https://jam.dev/c/15e4b2c6-75a7-4d4c-83fe-63ace295fa14

**Comment by fatchat** [comment]
1. create an operation node
2. click away from the node
3. (do stuff, load a preview of another model)
4. come back to the node
5. the platform responds with a `400: Operation not found`

**Comment by nairabhishek73** [comment]
https://jam.dev/c/14df92eb-751c-4a74-be3b-6acb0c6ef03b

**Comment by fatchat** [comment]
@nairabhishek73 i think this has been fixed i followed the steps-to-reproduce above and am not getting an error

**Comment by nairabhishek73** [comment]
Looks like its still active: https://jam.dev/c/d68749e3-90d8-49f8-be05-96c591ff06b5

**Comment by himanshudube97** [comment]
issue->
1. When i click a table then click the cast form, a ghost node appears (node not yet saved to db). When I click on the ghost node, the form resets , which should not happen. Ideally, when I click the ghost node, the cast form should remain there.
2.
