### ISSUE TITLE
Redesign drop function to allow select all and to match format of cast function

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1051]
<img width="409" alt="Screenshot 2024-07-26 at 4 12 22 PM" src="https://github.com/user-attachments/assets/df4a8364-6795-4f2c-b005-7b2a5e807fe6">

Adhyayan: Currently I need to type each name and then select it and then type the next name and select it.  This is very time consuming and difficulg

Instead of a dropdown could we have it more like the cast list with a search bar at the top and a select all checkbox.

So when I type ab, all the items with ab show up and I can hit the checkbox and select all.

Similarly if i type and somethings are selected and I want to unselect them, i hsould be able to view and do that easily.

**Comment by nairabhishek73** [comment]
https://jam.dev/c/a8024a4f-3f32-45af-b585-49fac61cdd7b

This is a common use case. Field names are related to form design which often will have a common start/end.

You will also notice that regardless of mouse or keyboard you need one click per column. The aim is to make it possible to select or unselect more than one item with one one click.

**Comment by fatchat** [comment]
We are going to ask T201 for an opinion / design

**Comment by Ishankoradia** [comment]
<img width="273" alt="Screenshot 2024-09-20 at 12 35 13" src="https://github.com/user-attachments/assets/1e4b2918-c984-4d46-b2e8-606a3ed06c60">

@nairabhishek73 let me know if this works ?
Changed the design to cast op form like. Checkbox besides search is for selectAll

**Comment by nairabhishek73** [comment]
Hi Ishan, as discussed with rohit I got designs for this from Think 201, please refer to this: https://www.figma.com/proto/qLRsjTZGNmoM1h1sy8alux/Dalgo-Designs?page-id=8474%3A34&node-id=8833-5718&node-type=frame&viewport=1110%2C372%2C0.27&t=XKANc6MJX7hn0V7d-1&scaling=min-zoom&content-scaling=fixed
