### ISSUE TITLE
Invitee on Dalgo needs signup code for signup

### ISSUE THREAD

**Issue by asldevi** [DalgoT4D/webapp#1058]
**Describe the bug**
Despite of receiving a invite, users are asked for signup code in the signup process. 

**To Reproduce**
1. Invite a user 
2. Click the invite link in the user's email
3. See the signup form

**Expected behavior**
To have the signup process smooth, either the invite should have a signup code or the signup form shouldn't have the code as a mandatory field.

**Comment by himanshudube97** [comment]
<img width="600" alt="Screenshot 2024-07-29 at 11 56 37" src="https://github.com/user-attachments/assets/78450583-e95a-45b9-9ad2-43470f002eba">

![Uploading Screenshot 2024-07-29 at 11.57.02.png…]()

The user might have clicked the signup button instead of just login, after accepting the invite.

**Comment by asldevi** [comment]
Looks like this was a false alarm. The user could resolve it via `Forgot password` as suggested.
