### ISSUE TITLE
not able to save rename with one column already selected

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/webapp#1060]
**Describe the bug**
I wanted to rename one column which I wanted to show it to client but I couldn't and gave me this error when I tried to save it. But when I add it another than it worked

<img width="363" alt="Screenshot 2024-07-29 at 10 55 47 AM" src="https://github.com/user-attachments/assets/d2d502e8-dfce-4bc7-9dbc-ef16ffba3fb2">

**Comment by fatchat** [comment]
i faced something similar - i turns out you have to hit ENTER after typing the new column name. then the second row appears and we are able to save

i know it is non-intuitive @mdshamoon is it easy enough to let the new column name be added to the state without the user pressing ENTER?

**Comment by fatchat** [comment]
@mdshamoon is this the at-least-one-required bug? i thought it was something to do with how the form is configured

**Comment by mdshamoon** [comment]
Yes @fatchat. The validation was not correctly added in the form for this. I have updated in this PR https://github.com/DalgoT4D/webapp/pull/1075
