### ISSUE TITLE
Move the Save Button

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1068]
When making changes to a table or functions inside the workflow view, the "SAVE" button is at the end of a long scroll in the case of a large table of a complicated function.

The "SAVE" button could be shifted to the top or floatinmg in the section for better accessiblity.

**Comment by nairabhishek73** [comment]
Adding here that the problem identified is that when a user edits a form, since the save button is not immediately visible, they may lick back and leave the changes unsaved. 

We had kept the save button at the bottom to ensure that the user does not hit save without completing the form. Now we have alerts if the form is incomplete so ok to have a floating save.

This on its own will not guarantee that folks press save after editing a function. 

If a user comes in to edit a function, makes changes, and presses back without saving they should be notified that they have unsaved changes and be asked if they wish to proceed.

**Comment by fatchat** [comment]
ok sure. note that the issue has been assigned so please put down whatever other details you need to today
