### ISSUE TITLE
Drop function edits

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1124]
https://jam.dev/c/7e1a344a-be1c-46f8-bee0-dc9239e287d4

Dalgo Demo

Configure drop
Press save
Go back
Make change and save or press save as it is,
 next form page does not come up

**Comment by fatchat** [comment]
https://www.figma.com/proto/qLRsjTZGNmoM1h1sy8alux/Dalgo-Designs?page-id=8383:1676&node-id=8383-6147&viewport=1048,495,0.17&t=Mj5Bq82ynSe7Im3R-1&scaling=min-zoom&content-scaling=fixed

**Comment by mdshamoon** [comment]
@nairabhishek73 this seems to be fixed with some other changes. Can you please check if its working fine now?

**Comment by mdshamoon** [comment]
> https://www.figma.com/proto/qLRsjTZGNmoM1h1sy8alux/Dalgo-Designs?page-id=8383:1676&node-id=8383-6147&viewport=1048,495,0.17&t=Mj5Bq82ynSe7Im3R-1&scaling=min-zoom&content-scaling=fixed

@fatchat creating a separate issue for this since this seems like an enhancement
