### ISSUE TITLE
incorrect order of dbt tasks

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/webapp#1138]
In Antarang's account, the default dbt tasks were in this order

![Image](https://github.com/user-attachments/assets/2aa33596-451c-4f7e-925a-e15456aeb365)

The configuration was `Simple`, I only clicked on `Advanced` to see the list

For now I have fixed the ordering in the prefect deployment `http://localhost:4200/deployments/deployment/933b361c-b20d-4048-90f7-98cdbd13aa2a`

**Comment by Ishankoradia** [comment]
Make sure the custom task like `dbt seed` are also in correct order. 
It should be right before `dbt run`

**Comment by fatchat** [comment]
Yes agreed. We had actually written that down in https://docs.google.com/document/d/1dvQOOg0dH4b91e7E-9T-tal6bRQrYbQmne7l2JP_pGE/edit#heading=h.98jebij8de8 where we listed `dbt seed` as a system task

we should create it as a system task which is not added to default pipelines
