### ISSUE TITLE
Update drop function

### ISSUE THREAD

**Issue by mdshamoon** [DalgoT4D/webapp#1141]
> https://www.figma.com/proto/qLRsjTZGNmoM1h1sy8alux/Dalgo-Designs?page-id=8383:1676&node-id=8383-6147&viewport=1048,495,0.17&t=Mj5Bq82ynSe7Im3R-1&scaling=min-zoom&content-scaling=fixed

@fatchat creating a separate issue for this since this seems like an enhancement

_Originally posted by @mdshamoon in https://github.com/DalgoT4D/webapp/issues/1124#issuecomment-2307045188_

**Comment by fatchat** [comment]
#1051
