### ISSUE TITLE
Enable selection of columns for a data stream in Connections tab

### ISSUE THREAD

**Issue by ashwinit4d** [DalgoT4D/webapp#1146]
Aitbyte allows users to select specific columns from a source for integration, rather than being required to integrate the entire dataset. With this added flexibility, users can now focus on the data most relevant to their needs, optimizing resource usage and efficiency. 

Dalgo should enable Airbyte’s feature to select/deselect columns for a particular stream through the Connections tab.

@jakejh

**Comment by Ishankoradia** [comment]
Already opened here - https://github.com/DalgoT4D/webapp/issues/1267

Will close this, since its a duplicate.
