### ISSUE TITLE
show name of connection in pipeline history view

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/webapp#1156]

**Comment by nairabhishek73** [comment]
Who has asked for this?

**Comment by fatchat** [comment]
Jake originally - their pipeline has several connections and in the history it just says

```
Airbyte sync
Airbyte sync
Airbyte sync
...
```

**Comment by nairabhishek73** [comment]
Hi based on this: https://jam.dev/c/53ba9507-af11-44c4-bc68-b84852a960d3

Could we do the following:
- Add column- c0onnection name. 
- Highlight row as red, if there is a failure.
- Can expand to see different tasks. The task which has the failure is highlighted as red.

**Comment by fatchat** [comment]
instead of adding a new column i was thinking we would replace "airbyte sync" with "<connection name> sync" within the existing column

to your other two points:

- view already shows different tasks
- we seem to currently show all as red instead of only the one which failed, we need to fix this

**Comment by nairabhishek73** [comment]
So instead of 'Airbyte sync ' it will say '*Connection name* sync' ?

**Comment by fatchat** [comment]
yes that's what i was thinking

**Comment by nairabhishek73** [comment]
Sounds good
