### ISSUE TITLE
Restrict connection options based on sync mode

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/webapp#1157]
1. When the `incremental` flag is set for a stream, require a `cursor field`

2. If no potential cursors are available for a stream, do not allow `incremental`

3. When the `incremental` flag is toggled off, select the sync mode to be `overwrite`. allow the user to change it but this should be the default state on load and on toggle-off

4. When the `incremental` flag is on, disallow `overwrite`

**Comment by himanshudube97** [comment]
1. `fixing issue` is the branch with the code to fix the issues. Had some confusion so closed the old branch.
