### ISSUE TITLE
Models not deleted when deleted from the UI4T canvas

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1186]
During the bangalore city meetup, whenever we would hit run we kept getting an error saying that x table is dependent on y table which does not exist even after deleting all the nodes on the canvas. Rohit then manually deleted from the back and then it worked.

**Comment by fatchat** [comment]
@Ishankoradia the .sql files were on disk but i neglected to notice their timestamps

don't know how to replicate either

**Comment by Ishankoradia** [comment]
@nairabhishek73 were there multiple people working on the canvas ( or the same org) ?

**Comment by nairabhishek73** [comment]
Yes

**Comment by Ishankoradia** [comment]
Since its a common canvas, multiple users working might mess up the models ?
1. Should we add a locking logic so that only one user can use ? 
2. Otherwise we will have to make multiple workflows for different user to work in - might be more complicated. 

@nairabhishek73 @fatchat

**Comment by fatchat** [comment]
we should lock the shared canvas. until then let's put this on hold

**Comment by fatchat** [comment]
i think it was just a matter of prioritization, we can bring it back

**Comment by nairabhishek73** [comment]
Lets knock it off sometime this quarter. Not urgent until we
successfully onboard a client for UI4T.
