### ISSUE TITLE
UI4T: Run to or from point

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1187]
"Run from node" is not an option when its from the first node. But this will be required if there are multiple chains of nodes with different starting points and I only want to run one chain.

<img width="1470" alt="Screenshot 2024-09-17 at 3 41 26 PM" src="https://github.com/user-attachments/assets/4e849c58-af57-4d15-8f13-d784553cb43c">

**Comment by Ishankoradia** [comment]
https://github.com/DalgoT4D/DDP_backend/pull/851

https://github.com/DalgoT4D/webapp/issues/1190
