### ISSUE TITLE
Pipeline failures, Test failures, trigger automatic notifications via notification system (also email and discord if activated)

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1193]
Currently only manually triggered notifications reach the user. 

@Ishankoradia @fatchat

**Comment by nairabhishek73** [comment]
@Ishankoradia could you share the timeline for this

**Comment by fatchat** [comment]
send notifications on success - make this a user setting

**Comment by fatchat** [comment]
Closing since there is no frontend work here
