### ISSUE TITLE
Ai analytics: Leave page mid prompt

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1203]
Not allowing me when I click leave anyway- https://jam.dev/c/1cc2844f-0f02-436a-9fa2-e9fdc7cc7312

**Comment by himanshudube97** [comment]
@nairabhishek73 please check this issue if it still persists. Its working fine for me.

**Comment by nairabhishek73** [comment]
Lets leave it open for now

**Comment by fatchat** [comment]
where are we on this

**Comment by himanshudube97** [comment]
> where are we on this

This issue we could not reproduce. Right now it works fine. 
Steps:
1. Generate an ai data analysis. 
2. Click on any other menu item in the sidedrawer (without saving)
3. Click Leave anyway button.
