### ISSUE TITLE
User predefined prompt, and editing of predefined prompts, or prompts in general, after the first submit.

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1207]
When I enter a user predefined prompt:
- Press the button, it goes from grey to green, then I need to hit submit, initially expectation was for it to just run. 
- Also the output is not great. 
- Instead lets 
1) Make the custom prompt box always open. 
2) Remove the 'or'.
3) And then when i hit summarise, the prompt behind the button should show up in the custom prompt box and then the user can edit or hit submit.
https://jam.dev/c/6f52de82-487f-4516-ba57-75f4bb58b920

Genrate output, then try to enter custom prompt and regenrate
- Allows me to enter custom prompt, does not allow me to hit submit.
- I should be able to edit the custom prompt area and submit again
- https://jam.dev/c/6b7c8c62-ce36-4f65-8f45-e6bdfba638d1

**Comment by himanshudube97** [comment]
@nairabhishek73 both done, removed the custom prompt button and also submit button is not disabled for querying again.
