### ISSUE TITLE
Use predefined prompt 'summarize' for qual descriptions of things (instead of decription of people's feelings)

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1214]
Could not test because of (https://github.com/DalgoT4D/webapp/issues/1213) 
This will probably not work but is solved for with issue: https://github.com/DalgoT4D/webapp/issues/1207

**Comment by Ishankoradia** [comment]
@nairabhishek73 can we close this since 1207 solves it.
