### ISSUE TITLE
Request formats of data- Table

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1216]
Doesn't work. Crucial for nonprofits who will ask for an output table and then want to copy-paste that somewhere.
Source: Antarang
https://jam.dev/c/527c129f-6cb1-4f2d-ac12-a045e1d34cd9

**Comment by himanshudube97** [comment]
@nairabhishek73 Data is being shown in a tabular format, but not with the rows and columns line. But the structure is tabular.  I ll check if i can enable the lines.

**Comment by nairabhishek73** [comment]
This works for now. Creating another issue https://github.com/DalgoT4D/webapp/issues/1231 for a table with lines. We can knock this off later.
