### ISSUE TITLE
Access saved session and edit it, then save as a new session

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1220]
"Its supposed to take me to a new pop-up when i click save as new. Instead it is using the same file name to save as new.
Ref 23 and 24 here: https://www.figma.com/proto/qLRsjTZGNmoM1h1sy8alux/Dalgo-Designs?page-id=7237%3A14450&node-id=7695-2371&viewport=2302%2C-285%2C0.35&t=J5FgerGI4J2z1NN5-1&scaling=min-zoom&content-scaling=fixed"

**Comment by himanshudube97** [comment]
@nairabhishek73 fixed this, when clicked save as new, a new save as pop will open
