### ISSUE TITLE
Check for permissions

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1223]
No permissions sought. Check https://www.figma.com/proto/qLRsjTZGNmoM1h1sy8alux/Dalgo-Designs?page-id=7237%3A14450&node-id=7796-141&viewport=2302%2C-285%2C0.35&t=J5FgerGI4J2z1NN5-1&scaling=min-zoom&content-scaling=fixed

This is pending some discussion as I don't think we'll do the entire settings menu now. But is certainly important. Will be figured out tomorrow and then will update this issue.\

@ashwinit4d

**Comment by Ishankoradia** [comment]
@nairabhishek73 remove the `hold` label and update the issue when you do the discussion with ashwini

**Comment by nairabhishek73** [comment]
Discussed. 
1) On first time visit to LLM insights let the disclaimer come us as in : https://www.figma.com/proto/qLRsjTZGNmoM1h1sy8alux/Dalgo-Designs?page-id=7237%3A14450&node-id=7796-141&viewport=2302%2C-285%2C0.35&t=J5FgerGI4J2z1NN5-1&scaling=min-zoom&content-scaling=fixed
2) Options avaialable on the disclaimer - Okay (Remove agree, disagree, and the cross)
3) Once they click okay they can use the feature

**Comment by himanshudube97** [comment]
@nairabhishek73 added the disclaimer page with only Okay button.
