### ISSUE TITLE
Inconsistent font sizes, check figma

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1226]
<img width="1154" alt="Screenshot 2024-09-23 at 6 37 30 PM" src="https://github.com/user-attachments/assets/367ac12b-46fe-4e16-984f-dfdc2370aed4">

https://www.figma.com/proto/qLRsjTZGNmoM1h1sy8alux/Dalgo-Designs?page-id=7237%3A14450&node-id=7556-1276&viewport=2302%2C-285%2C0.35&t=J5FgerGI4J2z1NN5-1&scaling=min-zoom&content-scaling=fixed

**Comment by himanshudube97** [comment]
@nairabhishek73 done as per the figma
