### ISSUE TITLE
If new session, then after unsaved sessions it should go to the save as popup, currently going to overwrite/saveasnew

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1230]
https://jam.dev/c/6f03b1cc-5167-4f07-b53d-28970c1b9d85

**Comment by nairabhishek73** [comment]
Hi @himanshudube97 what about this, https://github.com/DalgoT4D/webapp/issues/1233 is related

**Comment by himanshudube97** [comment]
@nairabhishek73 this is fixed.
