### ISSUE TITLE
Click on AI analytics after generating an insight

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1233]
https://jam.dev/c/42d1500b-3bc8-4155-84b6-68b4967c9381
https://jam.dev/c/6a440676-58b0-4e9b-be85-fec7bced250c

To reproduce, generate an insight, then click on llm insights
Edit: Click anywhere, why is it asking to overwrite when I have not accessed a saved session: https://jam.dev/c/e81fab53-abbb-4c1a-ae4c-992b1eb70a07

Also check if this bug happens after tweaking and submitting  a saved session

**Comment by himanshudube97** [comment]
@nairabhishek73 fixed this issue too.
