### ISSUE TITLE
Ai analytics doesn't seem to be working well on quant. 

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1240]
Set data types and sorted the data to check for australia, which falls in the limit, yet it isn't giving me accurate numbers.

Why is that?

Dalgo postgres on staging

https://jam.dev/c/196507c3-7814-4666-8c4b-2633f9647f21

**Comment by fatchat** [comment]
LLMs aren't great with arithmetic though right
Will not work on this until we understand their capabilities better
