### ISSUE TITLE
Delete columns if NULL

### ISSUE THREAD

**Issue by pratzrao** [DalgoT4D/webapp#1248]
As far as I'm aware, currently there is no way to DROP columns only if they contain no values. 
I don't want to hardcode it to always delete the column, since in the next sync it's possible more data comes in, in those columns.
We cannot always manually check to see if the columns are null or not before deciding to drop them and then alter the workflow after a sync.

**Comment by fatchat** [comment]
hi @pratzrao 

if the column may in future contain data then it shouldn't be dropped

so it sounds like column-dropping is not what you want

if you provide some more context i may be able to advise appropirately
