### ISSUE TITLE
Simplify orchestrate page logs

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1262]
The different tasks per row (especially the small DBT ones) is too much information off the bat, I would want to see one row, and then expand for more information.

**Comment by fatchat** [comment]
ok, so before expansion the columns would be

- date
- task = ? (maybe leave this blank?)
- total duration
- action = ?

where should we put the expand/collapse actions, do you want a caret to the left of the date

**Comment by Ishankoradia** [comment]
Closing this. Logs are grouped now.
