### ISSUE TITLE
Remove autocollapse of left menu bar for superset, superset usage, and data quality.

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1269]
Its more bothersome than it is helpful. Especially for folks who are coming to the platform for the first time or for folks who don['t have superset or elementary setup. 
For existing users with these features in use, they can learn to minimise on their own.

**Comment by huamanraj** [comment]
Hi @nairabhishek73 ,

I would like to work on this issue. Could you please assign it to me?

Thanks!

**Comment by himanshudube97** [comment]
> Hi @nairabhishek73 ,
> 
> I would like to work on this issue. Could you please assign it to me?
> 
> Thanks!


Hi, @huamanraj,

The issue was of high priority, so the team has resolved it. Thank you for your interest and willingness to assist.

**Comment by himanshudube97** [comment]
@fatchat This is the same issue that we discussed in the afternoon
