### ISSUE TITLE
All menu items to be unexpanded at the intial load and to default to unexpanded on reloads.

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1272]
Our left bar menu items are increasing, lets keep everything unexpanded- Pipeline overview and Analysis

**Comment by fatchat** [comment]
always in its default open state unless user manually minimise it

**Comment by himanshudube97** [comment]
<img width="978" alt="image" src="https://github.com/user-attachments/assets/474a5973-ff45-4b1c-a19c-53abd66aea86">
Done
