### ISSUE TITLE
Data Insights: Remove the store folder

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1273]
Let the scehmas folders be visible without needing to click on store

**Comment by nairabhishek73** [comment]
Replace the word store with Schemas and let all the schema folders be listed under it.

**Comment by himanshudube97** [comment]
@nairabhishek73 Kept the ui same. Changed the store to Schema. No need of clicking on schema to show all the schemas list, they  are rendered as soon as we open the Explore page. 

Kept the Folder icon in front of `Schema`. Without it there was empty space left which didn't look good.

<img width="351" alt="image" src="https://github.com/user-attachments/assets/303810d9-17ea-4a74-8cfc-0e90cbf894f0">

**Comment by nairabhishek73** [comment]
Sorry last change can you rename Schemas to 'Data'

**Comment by nairabhishek73** [comment]
Also make sure the same changes reflect in the data insights in the UI4T

**Comment by himanshudube97** [comment]
@Ishankoradia this was the issue.
