### ISSUE TITLE
Alignment of data insights as per figma

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1274]
Match alignment on data insights as per the figma: https://www.figma.com/proto/qLRsjTZGNmoM1h1sy8alux/Dalgo-Designs?page-id=8474%3A34&node-id=8474-530&node-type=frame&viewport=1110%2C372%2C0.27&t=XKANc6MJX7hn0V7d-1&scaling=min-zoom&content-scaling=fixed

Noptice the margins

**Comment by nairabhishek73** [comment]
<img width="940" alt="Screenshot 2024-10-17 at 4 58 08 PM" src="https://github.com/user-attachments/assets/835a1ee4-974b-44f2-9b27-d5acc976615c">

Its still not aligned. 

Also we should have the dalgo bar at the top, its there in Ui4T but not in the explore tab.

**Comment by himanshudube97** [comment]
@Ishankoradia 
As Nair pointed out, the alignment was off, and there was` no Dalgo bar at the top `in the explore tab but was in the ui4t. Both fixed.
