### ISSUE TITLE
llm data analysis feature optin for account managers is set to false by default

### ISSUE THREAD

**Issue by Ishankoradia** [DalgoT4D/webapp#1311]
1. Although the orgpreferences say that the llm_optin is False, the switch is already enabled. 

<img width="1495" alt="Screenshot 2024-11-16 at 12 42 20" src="https://github.com/user-attachments/assets/ffcb37fa-dfbd-48de-b352-091f582399a5">

2. Also clicking on the switch, it doesn't toggle off. Looks like we have set the value to true & state is  not changing.

**Comment by himanshudube97** [comment]
<img width="1158" alt="image" src="https://github.com/user-attachments/assets/4d40b53f-b151-4b11-8921-2b1d0f788028">

This issue was resolved and pushed yesterday. So there is an `org_preference.to_json `function , the data types for the boolean field was wrongly added as str, hence the issue.
