### ISSUE TITLE
roles below account manager should see some message on why discord settings is disabled

### ISSUE THREAD

**Issue by Ishankoradia** [DalgoT4D/webapp#1314]
<img width="798" alt="Screenshot 2024-11-16 at 13 20 31" src="https://github.com/user-attachments/assets/00f88dee-c04c-4f83-8a30-7762416aed3c">

1. Currently the toggle is disabled but a pipeline manager wont know why or what to do. There should be a message saying "they cant do it ,please contact their account managers"

2. Also, the disabled toggel should be off by default. Currently account manager hasn't enabled it but still it shows enabled & greyed out instead of disabled & greyed out.

**Comment by himanshudube97** [comment]
1. Added a Info tooltip here, so that users know why the button is disabled.
2. The issue was the wrong data type being sent from the backend. (fixed)
