### ISSUE TITLE
Notifying other account managers that AI Data analysis feature is now enabled. 

### ISSUE THREAD

**Issue by himanshudube97** [DalgoT4D/webapp#1316]
If one account manager enables the ai analysis feature, but another account manager sees the notification and then sees the feature is already enabled, it will confuse them or harm their user experience and trust in up-to-date notifications.

1. Send notifications to other account managers.
2. We have information about who enabled the ai llm settings in the backend. So we can display it on the ui.

**Comment by fatchat** [comment]
instead of sending the notification to account managers or to the feature requestor, just send it to everyone in the org

**Comment by himanshudube97** [comment]
@fatchat done. Sending notifications to all members of the org
