### ISSUE TITLE
Settings Panel - The end date should be removed from the Subscriptions for Annual Subscribers

### ISSUE THREAD

**Issue by ashwinit4d** [DalgoT4D/webapp#1330]
**Describe the bug**

This is a deviation from the Settings Panel scope.

For all the subscribed users, only the Start date should be mentioned. We do not have a concept of renewal. The subscription continues till the user decides to move away from the platform or we decide to terminate the contract

NO email should be triggered for the subscription users on completion of the subscription cycle.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Ishankoradia** [comment]
Closing this. It has been resolved.
