### ISSUE TITLE
Bigquery warehouse creation with gcs loading method shows duplicate form fields

### ISSUE THREAD

**Issue by Ishankoradia** [DalgoT4D/webapp#228]
## Description
When we add a new BigQuery warehouse  and select the Loading method as `GCS` and then toggle it a few times from `Standard` to `GCS`, we see multiple form fields for the same input like `GCS Secret ID`.

## Goals
- [ ] This should not happen

## Expected Outcome
The form should not have duplicate fields after toggling the loading method

## Acceptance Criteria
- [ ] Form should not have duplicate fields after toggling the loading method 

## Implementation Details
The main logic is in the file `src/helpers/ConnectorConfigInput.tsx`

## Mockups / Wireframes
This should not happen:
<img width="533" alt="image" src="https://github.com/DalgoT4D/webapp/assets/2160416/8cc845fa-cc7c-486b-8948-a59781d3bb6b">

### Product Name
Dalgo

### Project Name
Dalgo

### Organization Name:
Project Tech4Dev

### Domain
30  Others

### Tech Skills Needed:
JavaScript, React

### Mentor(s)
@fatchat 

### Complexity
High

### Category
Bug

### Sub Category
Frontend

**Comment by Ishankoradia** [comment]
The main logic is in the file `src/helpers/ConnectorConfigInput.tsx`

**Comment by Kushdapush** [comment]
Hey @Ishankoradia , I just came to know that @fatchat wants someone to work on this issue since he mentioned it in the C4GT community, I am very enthusiastic to work on this, could you please help me by assigning this issue to me!

**Comment by fatchat** [comment]
hi @Kushdapush , love the enthusiasm. go ahead and create a PR, don't worry about issue assignment etc

**Comment by Kushdapush** [comment]
Got it, thanks for this warm gesture 🙏
