### ISSUE TITLE
fetch running tasks on pipeline pages

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/webapp#255]
when a user visits one of

```
/pipeline/ingest
/pipeline/transform
/pipeline/orchestrate
```

, the page should fetch any jobs running on the platform which were triggered from that page, _even if triggered by another user_

if there is an active job, then
- the "run" button should be disabled
- the logs should be fetched and displayed (only if triggered by self? @vinod-rajasekaran @nairabhishek73 any opinion on this)

**Comment by nairabhishek73** [comment]
Seconded. If user X comes on and user Y has something running then it should show what's running and who has run it.

**Comment by fatchat** [comment]
show on the overview screen as well

**Comment by fatchat** [comment]
also put in a loading indicator when fetching run logs

**Comment by fatchat** [comment]
also in the pipeline overview, orange bars should show "dbt test failed" in the tooltip

**Comment by fatchat** [comment]
on the overview, if the pipeline is running replace the green tickmark + last run time with a loader and the text "currently running"

**Comment by fatchat** [comment]
for this ticket, we're going to stop at showing 
- that a task is running
- who started it
- when they started it

we will defer logs to a fresh issue

**Comment by nairabhishek73** [comment]
Solid first step. Sorry for the delayed review.
Ran manual prefect job via orchestrate page-
- It doesn't say triggered by whom on the DBT page.
- It could look a little nicer with better spacing from the borders and text above on the orchestrate section.
- It could look a little nicer with better spacing from the RHS border in the Transform section.
- When I am running the job and I hit last logs on orchestrate it doesn't say show me the job that's running or that there's a job running.

Ran source sync, could not execute DBT run during this time.
Executed DBT run, could sync sources. Then I think the DBT completed, sources still syncing, and now theres nothing showing on the DBT section: https://jam.dev/c/a013d88a-d503-4fb4-a7ab-15d685614e69

If i trigger a pipeline from orchestrate, on DBT it should say triggered by abhishek nair via orchestrate, same for on the sources page. This would apply for every permutation of action on a source page and corresposning message on aother page its affecting.

**Comment by fatchat** [comment]
1. can add triggered by whom, let's do this in conjunction with cleaning up the current design i.e. your next two points

4. when you are running which job, a dbt run?

the connection sync (from ingest) and dbt-run should be independent, so running one should not block the other. they're only tied together via the orchestration pipelines

"via orchestrate" hmm why
