### ISSUE TITLE
inconsistent display of source name and type

### ISSUE THREAD

**Issue by jakejh** [DalgoT4D/webapp#317]
When creating a connection, I specify the source based on its name, e.g., "rsurveycto_source". However, after creating it, I can only see the *type* of source, e.g., "SurveyCTO" or PyPI. This includes if I click edit and look at "Select source". Could be particularly confusing if someone creates multiple sources of the same type.

**Comment by fatchat** [comment]
Replace the source type with name + type, with the type in lighter text below

Replace the destination type with name + type, with the type in lighter text below

Show the warehouse name correctly i.e. the name entered in the creation form should match the one in the edit form

Show the warehouse name in the view above the icon

**Comment by nairabhishek73** [comment]
Warehouse name is not getting updated: https://jam.dev/c/81088f38-277a-4645-8485-28a20d47a6b6

**Comment by Ishankoradia** [comment]
It works , just change your tab or refresh the page. 
A fix on webapp is required to automatically refresh as soon as you update the name.

**Comment by nairabhishek73** [comment]
Is there a separate issue created for this?

**Comment by Ishankoradia** [comment]
No, can you please open one and assign for the upcoming sprint. Its a small one.
