### ISSUE TITLE
Prep for Webinar

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#326]

**Comment by fatchat** [comment]
make a detailed plan by 2023-08-30

**Comment by fatchat** [comment]
detailed plan by 2023-08-31

**Comment by fatchat** [comment]
@siddhant3030  to reach out to SNEHA STiR and SHRI for webinar 

- can we show their data
- would they attend and describe their use-cases
- would they demo the platform [?]

**Comment by fatchat** [comment]
Webinar scheduled for 2023-09-21

**Comment by fatchat** [comment]
Internal demo @nairabhishek73  on 2023-09-08 showing SNEHA charts without people's names / PII

**Comment by fatchat** [comment]
AN has asked Nadeem for permission to show dashboards

In parallel we will set up our own dataset

- look on kaggle
- look for health datasets
- set up dashboards in our superset

For the pipeline we will show one of our live clients dashboards

For Superset we will show the public dataset

**Comment by fatchat** [comment]
AN has found some datasets in Google Sheets, he will share and we will set up the pipelines for the demo

Two Google Sheets sources
dbt for normalization
and maybe a pivot table

**Comment by nairabhishek73** [comment]
Sheet 1: https://docs.google.com/spreadsheets/d/1MIdEYA3yKWcWQn05SmtNQ_svYXSBRA_mB8LbJVSrxJo/edit?usp=sharing
Sheet 2: https://docs.google.com/spreadsheets/d/18GqjB6nFBxZbAPnk6UOAvERE3iMfi4AkidjV6HkFKQk/edit?usp=sharing

On DBT- Union both datasets and process N/A as 'null'.

Filters:
NGO- Multi choice drop down
Month- Multi choice drop down
Indicator: Single select. Default to # of service contacs at NGO Partner clinics
SPOC: Multi choice

5 Key indicators: 

# of service contacts at NGO partners clinics
# of youth (15-25 years) accessing reproductive health services (PBG Indicator, reported quarter basis)
# of newborns born in supported clinics and catchment area receiving immediate newborn care (within 72 hours)
# of children less than 12 months of age who received DPT3/Penta3 from USG-supported programs
# of injectables provided through USG supported program to prevent unintended pregnancies

Visuals: 
(1) Key indicator sums- scorecard
(2) Key indicator trends- Multi line graph
(3) NGO rankings- Top 3 NGOs 

Setup role based security- each SPOC should only see their NGOs data

@Ishankoradia @fatchat
