### ISSUE TITLE
Terminology review on orchestration page

### ISSUE THREAD

**Issue by Ishankoradia** [DalgoT4D/webapp#337]
Putting down my thoughts.

- `Flows` should be called `Pipeline`. 
- In orchestration list page,  calling the column `Last scheduled run` is confusing since the last run can be scheduled or manual. 
- In the pipeline overview, we should replace `Flows` with `Pipeline`. Should we separate out the `manual` vs `scheduled` run.

**Comment by fatchat** [comment]
On the pipeline overview page, remove "Scheduled flows are operational" 

But keep the "no flows are available" box 

Replace "Overview" with "Pipeline Overview"

On the Orchestrate and Overview pages

- replace "Flows" with "Pipelines" everywhere


A Pipeline is 
- zero or more connections
- zero or one transformation
(but not both zero!)
- running on a schedule

**Comment by nairabhishek73** [comment]
Could we do away with this green bar altogether.

![Image](https://github.com/DalgoT4D/webapp/assets/119285990/12e8a0aa-5c6a-46d7-a1a3-76f25baa5885)

Could it say 'last run performed x minutes ago' just saying 'last performed x minutes ago' leaves one wondering what was performed.

**Comment by nairabhishek73** [comment]
Great, works, thanks!

**Comment by nairabhishek73** [comment]
In orchestration logs it still says flow runs


![Image](https://github.com/DalgoT4D/webapp/assets/119285990/004a855a-7efb-4863-8061-7118b5dec4a6)

**Comment by Ishankoradia** [comment]
<img width="842" alt="Screenshot 2023-09-08 at 9 21 04 AM" src="https://github.com/DalgoT4D/webapp/assets/39583356/b702030e-acd2-4ac7-81d2-0faf06f9cfc2">

Changed it to "Pipeline Runs"
