### ISSUE TITLE
Who can create new orgs

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#349]
One possibility: only the following can create new orgs
- t4d
- goalkeep
- agency fund

all other users are invited to an org created by one of the above

this means that the "signup code" will never be shared outside this group

and we remove the "create new org" action via ... user permissions or something

**Comment by nairabhishek73** [comment]
Could we align on the final plan for this tomorrow and then execute.

**Comment by vinod-rajasekaran** [comment]
maybe do this using a role in the front-end so future new data management orgs can have this feature instead of a hard code ;

**Comment by fatchat** [comment]
yes we have implemented this via something-like-a-role

**Comment by fatchat** [comment]
Signup page: Add
"Need a signup code? Contact Us href=https://dalgo.in/contact-us/"

**Comment by nairabhishek73** [comment]
Works
