### ISSUE TITLE
Make navigation bar on DDP UI collapsible

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#355]
## Description
The Dalgo UI has a sidemenu for navigation on the left

<img width="608" alt="image" src="https://github.com/DalgoT4D/webapp/assets/2160416/9aa029f0-4e10-4aac-b2e4-efd4b710eafd">

We would like the user to be able to collapse it to get more screen space

## Goals
- [ ] Make the sidemenu collapsible (and expandable)

## Expected Outcome
A new control (small, clickable) on the sidemenu which toggles collapsed <-> expanded

## Acceptance Criteria
- [ ] Side menu should be collapsible

## Implementation Details
The frontend is a NextJS application. I will provide you with a login to our backend so that you don't have to run a backend on your own system

## Mockups / Wireframes
None

### Product Name
Dalgo

### Project Name
Dalgo frontend

### Organization Name:
Project Tech4Dev

### Domain
Others

### Tech Skills Needed:
React, NextJS

### Mentor(s)
@fatchat 

### Complexity
Low

### Category
Feature

### Sub Category
Frontend, Beginner friendly

**Comment by huzaifmalik786** [comment]
Greetings, sir @fatchat , I have gone through the issue, and I would like to start working on it. Please assign it to me.

**Comment by fatchat** [comment]
glad to have you @huzaifmalik786 . i've added you as a collaborator to this project so that you can create a branch here instead of forking the repo. please accept the invitation

**Comment by huzaifmalik786** [comment]
Got it Sir. Thank you!

**Comment by huzaifmalik786** [comment]
@fatchat do I have to setup the backend as well locally to run the frontend server properly or is there any way I can avoid setting the backend codebase locally?

**Comment by fatchat** [comment]
@huzaifmalik786 in your `.env` you can set 

`NEXT_PUBLIC_BACKEND_URL="https://staging-api.dalgo.in"`

also set

```
NEXTAUTH_SECRET="<secret value>"
NEXTAUTH_URL=http://localhost:3000
```

(generate the secret using `openssl rand -base64 32` or something similar)

when you do this you will face a login screen. i will create an account for you, send me your email address on discord

**Comment by huzaifmalik786** [comment]
I've send you my email on discord.

**Comment by huzaifmalik786** [comment]
@fatchat I have a created a pull request which fixes the issue. I have also added a small demo video for your reference. Please review it. Thank You!
