### ISSUE TITLE
Show valid destination sync modes for connections form

### ISSUE THREAD

**Issue by Ishankoradia** [DalgoT4D/webapp#359]
Currently when we select the sync mode as `full_refresh` i.e. not toggling the incremental switch. We see all the destination sync modes, however we should only see `overwrite` and `append`. Whereas for the `incremental` sync mode, the options should be `append` and `append + dedup history`. Right now its not hiding the irrelevant options.

**Comment by fatchat** [comment]
Closed by #1164
