### ISSUE TITLE
Link Dalgo Documentation to UI and website.

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#374]
- Base version is simple links to documentation

1. Website- Top menu Bar, can take up with prod
2. UI- Overall "Help" or "Documentation" in the left pane.

- Advanced version 1 is little 'i' information marks near different aspect of the UI that link to the relevant subheaing of documentation
- Advanced version is the little 'i' information marks near different aspect of the UI that have chat bubble guides with a link to more info.

**Comment by Ishankoradia** [comment]
website is done.
