### ISSUE TITLE
Scroll back to top bug in connections form option setting

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#380]
https://jam.dev/c/d1b1fc54-c3ef-4596-be64-3ed9dc87728b

**Comment by Ishankoradia** [comment]
@nairabhishek73  @fatchat  instead of dyanmic search filter. Can we just do search and enter ? So they will type the stream name and hit enter after that.

**Comment by Ishankoradia** [comment]
Ignore the above comment. was able to fix it.

**Comment by nairabhishek73** [comment]
This is not fixed. Just tried on Testneworg4_SN on staging. Tagged you @Ishankoradia 

CC @fatchat

**Comment by fatchat** [comment]
maybe we misunderstood you, i did it just now on the LAHI "Andhra Sheet Connection" connection, scrolled down to "P12VT" and successfully toggled the switch without any scrolling of the form

Also changed "Append" to "Overwrite" for a few of them,

**Comment by Ishankoradia** [comment]
Seems to be working. @nairabhishek73 let us know if you were thinking something else.

**Comment by nairabhishek73** [comment]
https://jam.dev/c/d1570b08-c4af-4e94-a276-78af5fb4f7e4

**Comment by fatchat** [comment]
@nairabhishek73 invite us both to this org please

**Comment by Ishankoradia** [comment]
Tested on Nair's org. Works nicely in my browser. Which browser are you using ? @nairabhishek73

**Comment by nairabhishek73** [comment]
I'm using chrome. Maybe its a caching issue. Works fine when I tried from
safari and when i tried from another chrome browser.
