### ISSUE TITLE
unable to add a new warehouse

### ISSUE THREAD

**Issue by jakejh** [DalgoT4D/webapp#421]
**Describe the bug**
The window to add a new warehouse reloads without notice and clears all entered info. Even when this occasionally doesn't happen, I'm getting an error (see screenshot below).

**To Reproduce**
1. Click on add a new warehouse.
2. Select destination type BigQuery.
3. Try entering some info or just wait.
4. If able, click Save changes and test.

**Expected behavior**
Page does not reload, and instead waits for me to click on Save changes and test. Then the warehouse gets added properly.

**Screenshots**
![Image](https://github.com/DalgoT4D/webapp/assets/2295314/0d04f7b3-d18b-456c-b628-0058b17baefd)

**Desktop (please complete the following information):**
 - OS: macOS 13.6
 - Browser: chrome 118.0.5993.70

**Comment by fatchat** [comment]
ohhh that sounds frustrating. we'll take a look at it tomorrow

@Ishankoradia
