### ISSUE TITLE
preview of schemas and tables with a main panel (like bigquery)

### ISSUE THREAD

**Issue by Ishankoradia** [DalgoT4D/webapp#427]

**Comment by Ishankoradia** [comment]
Ashwini, Nair, Vinod and Rohit - to discuss/finalize the UI/UX process & let the developers know the next steps on the UI building.

@nairabhishek73 @vinod-rajasekaran  
@fatchat

**Comment by Ishankoradia** [comment]
Do research on tools that come closest to a automation/transformation and see what other tools are doing

**Comment by fatchat** [comment]
Dataform: frontend for dbt. Connect a GitHub repo, edit files and commit. Run the dbt transformation in the repo. Preview data in the warehouse

Palantir Foundry: Graphical workflow designer. Define a workflow which starts with a table, applies transformations and writes to another table. Transformations are represented as boxes connected by arrows, steps are at the granularity of

- split string
- take array element
- make uppercase
- add 5
- join array elements

etc

**Comment by fatchat** [comment]
dbt cloud: very similar to dataform. models on the left, editor on the right. compile / run buttons at the bottom. lineage graph.
