### ISSUE TITLE
Add Manual sync option to Orchestrate > Pipelines

### ISSUE THREAD

**Issue by swapneelrane** [DalgoT4D/webapp#451]
**Is your feature request related to a problem? Please describe.**
Cannot set pipeline for ONLY manual runs; am forced to select daily or weekly runs

**Describe the solution you'd like**
An option to set Manual runs (in addition to Daily & Weekly schedules)

![Image](https://github.com/DalgoT4D/webapp/assets/21273738/d1f77849-6b89-42f0-b070-d1d989d61c9a)

**Comment by fatchat** [comment]
what a coincidence... @Ishankoradia and i were just talking about enabling this

will keep you updated

**Comment by Ishankoradia** [comment]
@fatchat you want me to take this up ?
