### ISSUE TITLE
Cannot edit `Name`, `Connections`, `Transform Data ?` fields on an existing connection

### ISSUE THREAD

**Issue by swapneelrane** [DalgoT4D/webapp#452]
**Describe the bug**

**To Reproduce**
1. Go to 'Orchestrate'
2. Click on 'Edit' for an existing connection
3. Toggle value for 'Transform data'

**Expected behavior**
Allow users to edit these values

**Screenshots**
![Image](https://github.com/DalgoT4D/webapp/assets/21273738/c2744bc1-a96e-42b2-a240-0d70882c21aa)

**Comment by fatchat** [comment]
this is also by design, until editability is built you can delete and create a new pipeline. the only downside of this method is that you lose the run history of the original pipeline

**Comment by Ishankoradia** [comment]
We will do this in two steps
1) Make the name, connections and transform data fields editable. Make cron field optional - if no schedule is selected; the pipeline will need to triggered manually.
2) Add option to select models/tags while running the pipeline (need more planning).

**Comment by Ishankoradia** [comment]
For step i) created 3 PRs (webapp, backend, proxy) @fatchat
