### ISSUE TITLE
Ingest logs disappear if you navigate away from page

### ISSUE THREAD

**Issue by swapneelrane** [DalgoT4D/webapp#476]
**Describe the bug**
Ingest logs disappear if you navigate away from page

**To Reproduce**
1. Go to 'Ingest.'
2. Click on 'Sync'
3. Go to any other page on Dalgo and com back to  'Ingest'

**Expected behavior**
Logs are visible while sync is running and user can nagivate and search through logs of historical runs.

**Screenshots**
![Image](https://github.com/DalgoT4D/webapp/assets/21273738/2f0ed4be-acb1-4994-9686-8b6526b3f9f8)

**Comment by fatchat** [comment]
thanks, this is being enhanced as a part of #440
