### ISSUE TITLE
add custom dbt tasks to a pipeline

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/webapp#534]

**Comment by fatchat** [comment]
listing potential libraries here:

1. https://react-dnd.github.io/react-dnd/docs/tutorial
2. https://www.npmjs.com/package/react-draggable
3. https://www.npmjs.com/package/react-beautiful-dnd

the last one is the most promising

**Comment by fatchat** [comment]
(3) above is no longer maintained, instead we might use

4. https://github.com/hello-pangea/dnd

**Comment by fatchat** [comment]
@mdshamoon:

see `FlowCreate.tsx:onSubmit`, and in particular `transformTasks` in the `POST` payloads within

we are currently sending all tasks which have `generated_by == 'system'` (whenever the user sets `data.dbtTransform === 'yes'` via the toggle-switch)

you are going to remove the toggle switch and insteead show them the tasks, so they can select them for inclusion in the `POST` payload

selection of tasks has some rules, described in the last section of [this document](https://docs.google.com/document/d/1dvQOOg0dH4b91e7E-9T-tal6bRQrYbQmne7l2JP_pGE/edit#heading=h.98jebij8de8)


the figma design is [here](https://www.figma.com/proto/qLRsjTZGNmoM1h1sy8alux/Dalgo-Designs?page-id=4007%3A481&type=design&node-id=4267-43244&viewport=-5497%2C402%2C0.66&t=Tf8uyyKm9S4ASZlj-1&scaling=scale-down&mode=design)

**Comment by mdshamoon** [comment]
@fatchat I am thinking we should use https://www.npmjs.com/package/react-arborist only since we are already using this in the project tree and it has the functionality for drag and drop

**Comment by Ishankoradia** [comment]
@nairabhishek73  putting it on hold, as we need to align on this

**Comment by fatchat** [comment]
yes except can we please align this week and complete it

**Comment by nairabhishek73** [comment]
This is now aligned. And as per our discussion is slotted to complete this/next week
