### ISSUE TITLE
UI for transformation

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#541]
Feature doc: https://docs.google.com/document/d/1aZWQpaDRdIZo8NjrQFuZ_9PVgUgHqpT-lHky1uVC8d4/edit#heading=h.rynmht4zfxdr

Functionality vis-a-vis user journeys

Create workflow
- [x] Pick between UI and Github integration to create transform workflow https://github.com/DalgoT4D/webapp/pull/558
- [x] Pick schema and relevant table to start workflow [commit](https://github.com/DalgoT4D/webapp/pull/560/commits/8209f7213326a24fca9d94783ee6634ce2823b25#diff-1ff8464f541b0961d912e57c315672c4017bff94fe98108aa3f142e6d08bc04f)
- [x] Create workflow with one function (TBD)

Run workflow 
- [ ] Full, upstream from node, downstream to node
- [x] View errors in lower segment 

Preview
- [x] Preview selected table (sort, pagination)

- [x] Save Workflow

Edit workflow
- [x] Enter UI for transformation
- [x] Exit UI for transformation

Functions
- [x] Name new tables 
- [x] Rename columns
- [x] Select/Drop
- [x] Cast
- [x] Coalesce
- [x] Replace
- [x] Arithmetic operations 
- [x] Filter
- [x] Case operator
- [x] Group By
- [x] Table unions
- [x] Joins

Documentation

- [x] Short text on hover  https://github.com/DalgoT4D/webapp/issues/564
- [ ] Per function detailed on docusaurus (text+video) 

**Internal Reviews**

- [x] Demo 1- Mar 5, 2024
- Choose between github and UI
- Pick schema, pick table, preview
- One function at backend
- See new node for workflow

- [x] Demo 2- March 12th, 2024
- Create to edit full flow
- Internal testing

- [x] Demo 3- March 19th, 2024
- All functions
- Internal testing

- [x] Demo 4- March 26th, 2024
- Internal Testing
- Documentation and go-to-market collateral

- [x] Go to Market- April 1, 2024
- March 26th, 2024- Design user feedback form (quant+qual)
- April 1, 2024, Free trial account for user feedback on feature
- April 1, 2024- Blog post- What is the feature, link to documentation, invitation to email us for a free trial
- April 15, 2024- Webinar- What is the feature, link to documentation, invitation to email us for a free trial\]
- April ??, 2024- Newsletter inclusion

**Comment by nairabhishek73** [comment]
@fatchat @ashwinit4d

**Comment by fatchat** [comment]
@nairabhishek73 want to update this
