### ISSUE TITLE
Revisit minimised navbar for web app

### ISSUE THREAD

**Issue by vinod-rajasekaran** [DalgoT4D/webapp#562]
**Describe the bug**
1. Currently there are no mouseovers that indicate what the icon is once minimised
2.  Analytics top level and usage dashboard show same icon - this should be different 
3.  As more items are added to menu, worth considering a minimised menu that only shows the top level items and on click expands out the menu and accordions out the choices.

<img width="1470" alt="Screenshot 2024-03-02 at 9 35 41 PM" src="https://github.com/DalgoT4D/webapp/assets/23266611/13b0ca3a-dcda-4427-9b8d-fb87755be439">

**To Reproduce**
4. Click on '....'
5. Scroll down to '....'
6. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fatchat** [comment]
@nairabhishek73 could we get an icon for (2) please

**Comment by nairabhishek73** [comment]
Requested Vrushabh

**Comment by nairabhishek73** [comment]
![Usage_dashboard_svg](https://github.com/DalgoT4D/webapp/assets/119285990/d1453128-7232-490b-8b81-67ee38ddd2d5)

**Comment by fatchat** [comment]
```
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M14 21C13.7348 21 13.4804 20.8946 13.2929 20.7071C13.1054 20.5196 13 20.2652 13 20V12C13 11.7348 13.1054 11.4804 13.2929 11.2929C13.4804 11.1054 13.7348 11 14 11H20C20.2652 11 20.5196 11.1054 20.7071 11.2929C20.8946 11.4804 21 11.7348 21 12V20C21 20.2652 20.8946 20.5196 20.7071 20.7071C20.5196 20.8946 20.2652 21 20 21H14ZM4 13C3.73478 13 3.48043 12.8946 3.29289 12.7071C3.10536 12.5196 3 12.2652 3 12V4C3 3.73478 3.10536 3.48043 3.29289 3.29289C3.48043 3.10536 3.73478 3 4 3H10C10.2652 3 10.5196 3.10536 10.7071 3.29289C10.8946 3.48043 11 3.73478 11 4V12C11 12.2652 10.8946 12.5196 10.7071 12.7071C10.5196 12.8946 10.2652 13 10 13H4ZM9.5 11.2929V4.5H4.5V11.2929H9.5ZM4 21C3.73478 21 3.48043 20.8946 3.29289 20.7071C3.10536 20.5196 3 20.2652 3 20V16C3 15.7348 3.10536 15.4804 3.29289 15.2929C3.48043 15.1054 3.73478 15 4 15H10C10.2652 15 10.5196 15.1054 10.7071 15.2929C10.8946 15.4804 11 15.7348 11 16V20C11 20.2652 10.8946 20.5196 10.7071 20.7071C10.5196 20.8946 10.2652 21 10 21H4ZM4.5 19.5H9.5V16.5H4.5V19.5ZM14.5 19.5H19.5V12.5H14.5V19.5ZM13 4C13 3.73478 13.1054 3.48043 13.2929 3.29289C13.4804 3.10536 13.7348 3 14 3H20C20.2652 3 20.5196 3.10536 20.7071 3.29289C20.8946 3.48043 21 3.73478 21 4V8C21 8.26522 20.8946 8.51957 20.7071 8.70711C20.5196 8.89464 20.2652 9 20 9H14C13.7348 9 13.4804 8.89464 13.2929 8.70711C13.1054 8.51957 13 8.26522 13 8V4ZM14.5 4.5V7.5H19.5V4.5H14.5Z" fill="#7D8998"/>
</svg>
```

**Comment by fatchat** [comment]
(1) and (2) to be done via https://github.com/DalgoT4D/webapp/issues/758
