### ISSUE TITLE
Preview of last table retained when clicking on blank space

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#590]
https://jam.dev/c/0ef69503-45f1-417f-b277-32ccc4a9547a

**Comment by nairabhishek73** [comment]
<img width="1470" alt="Screenshot 2024-03-18 at 12 18 24 PM" src="https://github.com/DalgoT4D/webapp/assets/119285990/bd240587-4c9e-410c-b266-53115ad08c27">

Preview also retained when there is no table in the workspace

**Comment by nairabhishek73** [comment]
Hi please check: https://jam.dev/c/99d617ce-657d-42ce-a0dc-13c48f976c11

**Comment by fatchat** [comment]
please check again

**Comment by Ishankoradia** [comment]
@nairabhishek73 please verify this again and close if its fixed. Thanks.
