### ISSUE TITLE
UI Transform- Cannot view data types for all columns- enable scrolling

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#591]
<img width="1470" alt="Screenshot 2024-03-18 at 12 20 39 PM" src="https://github.com/DalgoT4D/webapp/assets/119285990/e0957c82-028f-41da-8ba2-acc50b2c150b">

**Comment by fatchat** [comment]
@nairabhishek73 please see now

**Comment by nairabhishek73** [comment]
Working! Thank you
