### ISSUE TITLE
UI tweaks/enhancements for transformation feature

### ISSUE THREAD

**Issue by Ishankoradia** [DalgoT4D/webapp#592]
Design link: https://www.figma.com/proto/qLRsjTZGNmoM1h1sy8alux/Dalgo-Designs?page-id=702%3A1809&type=design&node-id=4234-9158&viewport=392%2C-2430%2C0.18&t=BehgU3jh5viVp2rw-1&scaling=scale-down

- [x] 1. Make sure the table nodes are scrollable and override the canvas behaviour of zoom in & zoom out. #591 
- [x] 2. Matching borders & spacing for the editor window at `workflow/editor` according to the figma
- [x] 3. Add correct color scheme in the editor window at `workflow/editor`
- [x] 4. Style (color + font + typography) the UI for operation form(s) according to the designs. 
     - [x] 4.1 Create common UI components that can be used across multiple operation forms
- [x] 5. Add a navigation (cross button according to the figma at the top right) in the editor window `workflow/editor` to go back to `pipeline/transform`
- [x] 6. The background highlight doesn't match the text of a selected tree option in Project Tree Component. 
<img width="335" alt="Screenshot 2024-03-18 at 22 28 20" src="https://github.com/DalgoT4D/webapp/assets/39583356/df7448a4-2dae-489c-a493-54f4e2146d1e">

@fatchat

**Comment by fatchat** [comment]
@mdshamoon could you update the list please, i think you've done it but you would know better
