### ISSUE TITLE
Transform UI- Google sheets data is unflattened

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#593]
https://jam.dev/c/e03b236b-ba13-40e3-b681-085631bdd2d6

**Comment by fatchat** [comment]
is this a new workspace? the destination has to be set up with "destinations v2" explicitly enabled

if you give me the workspace id i can enable it for you

**Comment by nairabhishek73** [comment]
Hi I invited you to the org! Its called UI testing.

**Comment by fatchat** [comment]
Oh I see what the issue was - in your video you were in the airbyte_internal schema, that's where unflattened data lives

everything is set up correctly, your staging schema has flattened data
