### ISSUE TITLE
Transform UI- Rename

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#594]
1) Keep the tables all foldered in store.
2) New function appears behind table.
3) Once you delete the function the delete sign isn't there on the preceding table.
4) Rename is generating the new line on current name selection it should do so after new name selection
5) Cursor should move to adjacent new name box after current name selection. 

https://jam.dev/c/0dcd9f4b-cd2f-408f-98cc-018c8f34a6fb

**Comment by fatchat** [comment]
Don't want blank rows in the middle see https://github.com/DalgoT4D/webapp/issues/660

**Comment by fatchat** [comment]
@nairabhishek73

**Comment by nairabhishek73** [comment]
- [ ] Keep the tables all foldered in store.
- [ ] New function appears behind table.
- [ ] Once you delete the function the delete sign isn't there on the preceding table.
- [ ] Rename is generating the new line on current name selection it should do so after new name selection
- [ ] Cursor should move to adjacent new name box after current name selection.

**Comment by Ishankoradia** [comment]
@nairabhishek73 yes, please split the two into new issues

**Comment by nairabhishek73** [comment]
- [ ] https://github.com/DalgoT4D/webapp/issues/770
- [ ] https://github.com/DalgoT4D/webapp/issues/771
