### ISSUE TITLE
Transform UI- Cannot add a table more than once.

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#596]
https://jam.dev/c/5d712bef-267d-4550-9700-3251ee5d57ee

**Comment by Ishankoradia** [comment]
@nairabhishek73  this is by design. We dont allow adding duplicate nodes of same table/model in the canvas/graph. 

If you want to create a new chain with the same table, click on the table and add operation.

**Comment by nairabhishek73** [comment]
Understood!
