### ISSUE TITLE
UI transform: All tables deleted when only one should be deleted

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#600]
https://jam.dev/c/04df47e3-ebc4-4f1d-8231-e8f86e410b84

**Comment by Ishankoradia** [comment]
This should fix it @fatchat  

https://github.com/DalgoT4D/webapp/pull/616

**Comment by nairabhishek73** [comment]
This seems fixed, is it?

**Comment by fatchat** [comment]
looks like it @nairabhishek73 please close if you think so too, i did what you did in your video and now the tables get deleted individually and don't reappear when the graph is refreshed
