### ISSUE TITLE
UI Transform: Arithmetic operation failed to create a table

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#601]
https://jam.dev/c/44434944-1674-48b7-b0d3-244ec9cf4954

**Comment by fatchat** [comment]
you were trying to add text columns 

1. with log-parsing we could detect this error and tell the user that they have to cast before adding ... this sounds useful but is a project by itself
2. we could prevent them from selecting non-numeric columns as the parameters to arithmetic operations

@Ishankoradia we have `ColumnData` in the op, could we filter the columns shown in the AutoComplete

**Comment by Ishankoradia** [comment]
@fatchat  using `ColumnData` could work for the first operation but not subsequent in the chain since we only track columns and not their data types in our chain. We could start doing it but this will be a big change.

**Comment by nairabhishek73** [comment]
As per our original discussion we just needed a warning. And if triggered warning was not possible then a disclaimer "Please ensure you only select numeric columns"

**Comment by fatchat** [comment]
something like this? @nairabhishek73 

<img width="330" alt="image" src="https://github.com/DalgoT4D/webapp/assets/2160416/0d0c0ec0-2edf-49be-bd83-00d20b40a10c">

**Comment by nairabhishek73** [comment]
![Uploading Screenshot 2024-03-22 at 12.25.30 PM.png…]()
Something like this
