### ISSUE TITLE
UI Transform: Replace

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#603]
https://jam.dev/c/79a6cbb0-3c49-4ca7-8877-a4dd8be3791c

Refer to the figma design- https://www.figma.com/file/qLRsjTZGNmoM1h1sy8alux/Dalgo-Designs?type=design&node-id=2927-794&mode=design&t=oVpuJfoOrQ0oesvA-0

Should be able to add replace for multiple values in a single column.

**Comment by nairabhishek73** [comment]
You will notice the figma has a grid in place and the save button at the bottom of the grid. 
For now could we maintain the grid with at least 5 rows of input boxes existing. More can appear on pressing enter.
Beyond that will speak to Vrushabh and get designs then we can fix.

**Comment by fatchat** [comment]
if we're putting a plus then why are we showing five empty rows?

**Comment by nairabhishek73** [comment]
To save them the effort of adding new rows if they don't have more than 5 replacements to do.

**Comment by fatchat** [comment]
@Ishankoradia the current implementation doesn't show a grid, is this part of what shamoon will be doing? if so then we will get it without adding a plus-button - the grid has X rows already and when they get to the last one we can add another after

**Comment by nairabhishek73** [comment]
Yes this works. Please ensure the cursor doesn't pop over to the newly added row prematurely.

**Comment by Ishankoradia** [comment]
Yes shamoon is working on this. Will be merging his PR, that has the UI grid component.

**Comment by fatchat** [comment]
https://github.com/DalgoT4D/webapp/issues/703
