### ISSUE TITLE
Ui Transform: Join is not saving

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#604]
https://jam.dev/c/8dd6ed16-e9f6-43a5-a143-3e7bf0fd6f34

**Comment by fatchat** [comment]
@Ishankoradia from the logs:
`dbt_automation.utils.tableutils.source_or_ref() argument after ** must be a mapping, not list`
this may be coming from `joins.py:93` or `:101`

**Comment by fatchat** [comment]
@nairabhishek73 please have another look

**Comment by nairabhishek73** [comment]
Could you suggest two datasets? the dataset I had ingested for joinining is not showing in file explorer ref https://github.com/DalgoT4D/webapp/issues/622
