### ISSUE TITLE
Cannot see ingested table in file explorer

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#622]
https://jam.dev/c/19612ecb-a182-49fc-9427-44c63c3ced92

**Comment by fatchat** [comment]
was this on creation of a new dbt workspace? if so it's possible the sources were still syncing

if not then we'll have to figure out how to reproduce

<img width="247" alt="image" src="https://github.com/DalgoT4D/webapp/assets/2160416/f0fd4dfb-80e8-4d1c-a38d-902fc3990900">

**Comment by nairabhishek73** [comment]
No its well after the creation of the workspace. Even now I cannot see one source.

https://jam.dev/c/4f8150e7-c899-4c76-b482-a42cea166251

**Comment by fatchat** [comment]
table `1_text` exists in warehouse
source `1_text` exists in `sources.yml`

**Comment by fatchat** [comment]
`OrgDbtModel` does not exist for `1_text`

**Comment by fatchat** [comment]
steps to reproduce:
1. click on a source to add node to workspace
2. delete the node
3. the `OrgDbtModel` gets deleted in the database

we should not delete if `type='source'`
