### ISSUE TITLE
Screen flashing when opening platform and when opening transform section

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#623]
https://jam.dev/c/361e6014-7d8a-4595-891f-40858620fc7f

**Comment by fatchat** [comment]
duplicate of #618

**Comment by nairabhishek73** [comment]
Its still happening though.

https://jam.dev/c/3b30d007-960e-45f0-9778-0e0d7493ed2b

**Comment by fatchat** [comment]
Yes yes it's a duplicate
