### ISSUE TITLE
UI Transform: Table retained even after deleting.

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#624]
https://jam.dev/c/361e6014-7d8a-4595-891f-40858620fc7f

**Comment by fatchat** [comment]
cannot reproduce after cleaning up the old workspace... it's possible it was a "dangling object" which was cleaned up

please see if you can reproduce now

**Comment by nairabhishek73** [comment]
Cannot reproduce. Will open a new issue if it comes up again.
