### ISSUE TITLE
First page of transformation is zoomed out 

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/webapp#629]
This is what I see when I go to transform page to choose the type of transformation. 

<img width="1258" alt="Screenshot 2024-03-22 at 10 37 59 AM" src="https://github.com/DalgoT4D/webapp/assets/9019958/7ac2a710-26ca-4157-8646-e477a7c55008">

adding one more screenshot 

<img width="1512" alt="Screenshot 2024-03-22 at 12 04 07 PM" src="https://github.com/DalgoT4D/webapp/assets/9019958/0f866be4-72ea-4dc7-bd27-0896c3af78c8">

**Comment by fatchat** [comment]
can you get the entire screen in the shot please, it's not clear what you're trying to show

including menu, navbar

**Comment by siddhant3030** [comment]
> can you get the entire screen in the shot please, it's not clear what you're trying to show
> 
> including menu, navbar

Have added one more screenshot

**Comment by fatchat** [comment]
ok understood - the two boxes are not fitting inside the screen
