### ISSUE TITLE
Operations on the table are supported even after the table is deleted

### ISSUE THREAD

**Issue by ashwinit4d** [DalgoT4D/webapp#630]
To reproduce the bug do the following

Select Table sheet4
Select an operation on the table. Now delete the operation bubble. The table gets deleted as well.
The operation panel on the right remains and allows the user to complete any operation on the table

**Comment by Ishankoradia** [comment]
This has been fixed and pushed to staging. @nairabhishek73  or @ashwinit4d  please test this.

**Comment by nairabhishek73** [comment]
tested, works. @ashwinit4d please reopen if you test and have a different result
