### ISSUE TITLE
Highlight around selected table or function is missing.

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#635]
Please refer to Figma

**Comment by fatchat** [comment]
@nairabhishek73 ready for review

**Comment by fatchat** [comment]
Whoops hold off please I'll get back to you

**Comment by fatchat** [comment]
@nairabhishek73 ok go for it

**Comment by nairabhishek73** [comment]
Selected table is hoighlighted but when new node is created it doesn't appear and isn't highlighted.

**Comment by nairabhishek73** [comment]
https://staging.dalgo.in/pipeline/transform

**Comment by fatchat** [comment]
highlight disappears upon save @mdshamoon

**Comment by mdshamoon** [comment]
We are refreshing the graph on save @fatchat. I am not really sure why we are doing that. Possible to have a quick discussion on this?

**Comment by Ishankoradia** [comment]
@mdshamoon  when we hit save on any operation; we see a page with two options `Create Table` or `Add Function`. At this stage, the node is supposed to be selected because you can still press `Add function` to chain more operations. 


This will be fixed in the edit-PR. You can take a pull and see it once; keep chaining operations.

**Comment by mdshamoon** [comment]
> @mdshamoon when we hit save on any operation; we see a page with two options `Create Table` or `Add Function`. At this stage, the node is supposed to be selected because you can still press `Add function` to chain more operations.
> 
> This will be fixed in the edit-PR. You can take a pull and see it once; keep chaining operations.

I get if we save an operation it should be highlighted because we can perform some other operation. We were redrawing the graph after save which changes the structure of the flow. I was not sure why we were doing that. 

@Ishankoradia works fine in the edit PR. Thanks
