### ISSUE TITLE
Cannot view connected sources in the file explorer

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#638]
https://jam.dev/c/dfd20d2a-bf83-4a14-a254-3afed0fb8128

The two tables and schemas you see are ones that were there when I setup the warehouse and checked without any connections, refer https://github.com/DalgoT4D/webapp/issues/639

**Comment by nairabhishek73** [comment]
1) new org- attempt to enter DBT workspace- blocked
2) Setup warehouse- attempt to enter DBT workspace - entered- sa two schemas and two tables
3) Setup 2 sources and relevant connections to new schema, synced them- enter DBT workspace- cannot see new tables in file explorer 

Need to setup everytime someone enters the workspace.
Need to add sync connections button to workspace screen in the file explorer section next to store.

**Comment by fatchat** [comment]
sorry why has this been labelled as a bug
this is the currently defined behavior
removing the label

**Comment by Ishankoradia** [comment]
@nairabhishek73 please verify this issue. We have added a sync button now and its pushed to staging

**Comment by nairabhishek73** [comment]
Works great. Thanks!
