### ISSUE TITLE
UI Transform: Warehouse setup, can only see two tables in two schemas in file explorer

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#639]
https://jam.dev/c/db82696b-5814-44cd-b572-b5bef71d8dcc

**Comment by Ishankoradia** [comment]
@nairabhishek73 please verify this issue. The bug is also fixed and you should see all tables in the warehouse when you setup your workspace. 
If you add a new connection after setup of UI method, there is a sync button that can be used to add new tables to the file explorer.

**Comment by nairabhishek73** [comment]
yes works
