### ISSUE TITLE
Ui Transform: Function addition bugs- add one function, add two functions

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#643]
1) function-node hidden behind table node- https://jam.dev/c/075097ec-5690-4c85-97c2-7f7f3cd5f863
2) Second function node not linked to preceding function node- https://jam.dev/c/fc08fd31-2a04-4542-a45a-6087f1665cfa

**Comment by fatchat** [comment]
@mdshamoon would you look at this please

**Comment by Ishankoradia** [comment]
@fatchat i am taking this over.

**Comment by Ishankoradia** [comment]
Not able to reproduce 2) 

This should fix 1) https://github.com/DalgoT4D/webapp/pull/653

**Comment by nairabhishek73** [comment]
Can skip 2)

Current functionality of 1) https://jam.dev/c/9279072b-c452-445e-a4f7-1e73ffdc4a79 after 653 merge

Notice how the table and function are appearing on different parts of the screen with every action.

**Comment by fatchat** [comment]
when a new source is added it goes waaaay off to the right
when we start adding sources vertically this should go away

**Comment by fatchat** [comment]
@nairabhishek73 have a look please

**Comment by nairabhishek73** [comment]
When I add a function node it is created to the bottom of the preceding node, when I save it, it hops to the right of the node. It should stay in one place, to the right, on creation and save.

**Comment by nairabhishek73** [comment]
Overall the layout should remain as it is, no existing nodes should move from where I have kept them. When I create a table here the entire arrangement went back to the default.
https://jam.dev/c/68b322f6-1ff7-49cb-a88a-329f83ff376f

**Comment by fatchat** [comment]
@nairabhishek73 

Moved your latest comment into https://github.com/DalgoT4D/webapp/issues/740

Can this one be closed, the original bugs reported have been fixed

**Comment by Ishankoradia** [comment]
@nairabhishek73
