### ISSUE TITLE
Can't drop columns more than eight

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/webapp#646]
Currently for the drop column I can select upto 8. For atecf I need to drop more than that in a single go. Can we not limit this? 

<img width="361" alt="Screenshot 2024-03-23 at 5 36 24 PM" src="https://github.com/DalgoT4D/webapp/assets/9019958/fb374b47-1b90-4f26-89ec-ed4cde700801">

**Comment by fatchat** [comment]
hi @siddhant3030 
i tried just now and i got up to 15 columns before stopping
would you try again, i don't think there is any limit

**Comment by siddhant3030** [comment]
@fatchat Oh I got it what's the issue. 
1. I'm not getting a clear indication whenever I'm adding after 5 or 6 
2. Order is changing the last one I selected goes to the top hence my thought is its not added 

<img width="348" alt="Screenshot 2024-03-23 at 8 37 53 PM" src="https://github.com/DalgoT4D/webapp/assets/9019958/466c53a3-1c66-4a30-bd66-5c2836db587f">
<img width="341" alt="Screenshot 2024-03-23 at 8 37 58 PM" src="https://github.com/DalgoT4D/webapp/assets/9019958/abc82381-b56e-40c3-be1e-1a7e053daeaa">


like if you see here so user will do the same mistake and they will keep clicking on the same column expecting it to be added at the end. 

So i think ordering will fix it. Thanks

**Comment by fatchat** [comment]
@Ishankoradia

**Comment by Ishankoradia** [comment]
@fatchat  can we close this. Its fixed.

**Comment by siddhant3030** [comment]
@Ishankoradia read my above comment

**Comment by Ishankoradia** [comment]
> @Ishankoradia read my above comment

i dont understand Sid.

**Comment by siddhant3030** [comment]
This is fixed now we can close this
