### ISSUE TITLE
UI Transform: Form retained if the function-node is deleteded while configuring the form

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#647]
https://jam.dev/c/e0603b24-9966-4132-8eb5-5c1f36497ca9

Not only this, but the form is also active, so i can continue to configure the form and then the function node is created if I press save. When the node is deleted, the form should disappear.

**Comment by fatchat** [comment]
hi @nairabhishek73 this should be fixed now

**Comment by nairabhishek73** [comment]
yes fixed thanks
