### ISSUE TITLE
Can't change the multiple cast timestamp values

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/webapp#649]
https://github.com/DalgoT4D/webapp/assets/9019958/37e255ab-cc25-4236-9eb0-a39084a28892

In this video I'm trying to do a cast on multiple timestamp columns but upon selecting the other one it changes to the same type.

**Comment by fatchat** [comment]
@siddhant3030 can close?

**Comment by siddhant3030** [comment]
yes
