### ISSUE TITLE
UI Transform: All dropdowns with column names to be in alphabetical order.

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#651]
<img width="372" alt="Screenshot 2024-03-24 at 1 58 15 PM" src="https://github.com/DalgoT4D/webapp/assets/119285990/6e9bb64f-0e41-4c0a-9157-111ed5e0589b">

**Comment by nairabhishek73** [comment]
Also all function names in alphabetic order.

**Comment by fatchat** [comment]
function names will be done in #657
