### ISSUE TITLE
Edit operations node creates a separate branch - this should be restricted

### ISSUE THREAD

**Issue by ashwinit4d** [DalgoT4D/webapp#659]
**To Reproduce**
Select table "sheet 2"
Select "drop" operation on the table and save the table
Now, select the operation node, this allows to add another operation, say "replace"
Now a new branch is created

**Expected behavior**
Edit operation node should not be supported once the table is materialized

**Screenshots**
<img width="1470" alt="Screenshot 2024-03-25 at 12 09 16 AM" src="https://github.com/DalgoT4D/webapp/assets/149574464/ca197f4e-2ca0-4aaa-958d-43d34ec1de4c">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fatchat** [comment]
No actions should be available on nodes from which an edge emanates
