### ISSUE TITLE
Rename form entry bugs

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#660]
When I pick my first column, a second input row is created and the rename typing cursor goes to the right column of that row.
- https://jam.dev/c/868e6943-c50c-427a-9594-bad6002e2302
Deleting an intermediate rename in the form- Just leaves a blank space there, entries from below should come up.
- https://jam.dev/c/363f89eb-f9b8-455e-a161-1ba91e6bac07

**Comment by fatchat** [comment]
(1) is from https://github.com/DalgoT4D/webapp/issues/594
(2) is new
