### ISSUE TITLE
Cast bugs/issues

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#664]
Please note this is an important function for any user to be able to use important value-type dependent functions. Please prioritise 2,3,4 - 2 and 3 are basically the same

1) Cast string as date- Function should not allow me to do this. If allowing then there should be a warning about this. Logs should show me clearly what i've done wrong	
- https://jam.dev/c/e6f1ba69-637a-4b3d-a1cf-49bd920ec5ab
2) Cast strings as float- Can only do one at a time, selection keeps toggling back. Noticed that actually it works for multiple but on the screen the type seems to be flipping back.
- https://jam.dev/c/0ef0ecdb-88f3-48f8-957a-aeda70d55b02
3) Select change- Selection for cast is flipping back to default everytime i click elsewhere	https://jam.dev/c/8bde2b8e-fded-4753-b975-068b6d2cb97a
4) Cast all character columns as float- Casted as float but then in the table-node it shows as "double precision" - nomenclature should be consistent (first) and easyt to understand (second)	
5) We had discussed showing limiited value types, instead now we are showing many more than a semi-technical user would know about

**Comment by fatchat** [comment]
overlap with #649

**Comment by fatchat** [comment]
@nairabhishek73 
1. cast string to date is a valid operation, the string just needs to be in a proper format
2. #649 
3. #649 
4. this is a postgres thing:

<img width="480" alt="image" src="https://github.com/DalgoT4D/webapp/assets/2160416/4838b4f9-ab6f-4815-bc1c-cfdc27f63aa7">

, we ask for a cast to `float` (which is a valid ask) and postgres calls it `double precision`. it's a bad idea for us to hide data types from the user, tempting though it may be

5. we are showing all data types supported by the warehouse - the types for postgres and those for bigquery are different. we could in future show common types up top and then other types below


so (1) should be addressed via documentation, (2) and (3) are duplicates, (4) is a feature and (5) needs further planning for a future release

closing this issue
