### ISSUE TITLE
cannot delete additional cases

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#669]
1) Single case with column compare to value- Output column name is not taken- check preview
2) Else statement is a column- Fail- Should have warning that both value types need to be the same- I did if active cases between 500 and 1000 then less, else active cases.
3) Delete Case- No option to delete second case if i add it but then decide I don't want it. Cannot save. must delete the whole function and start again

**Comment by fatchat** [comment]
1. duplicate of #655 
2. what you did is valid i.e. mixing columns and values
3. this sounds annoying

renaming issue to "cannot delete additional cases"

**Comment by nairabhishek73** [comment]
for 2- then why didn't it work?

**Comment by fatchat** [comment]
in your video did you try to cast "senegal" to a date

**Comment by Ishankoradia** [comment]
@mdshamoon  we can do the 3)

**Comment by nairabhishek73** [comment]
Here is the video for 2) https://jam.dev/c/c0db8768-ba4a-4164-9571-f23901974658

The aim is for me to be able to run a condition to achieve this-
-- If meets the criteria then *specific output in cell* else row value remains unchanged

**Comment by fatchat** [comment]
@nairabhishek73  ah this is what went wrong - you are allowed to mix columns and values BUT the data type of the value must match that of the column
