### ISSUE TITLE
arithmetic failing

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#670]
Additioon- column	Failing- https://jam.dev/c/17c721db-e50b-4929-ad7a-d22ad88f65a6
Addition- column value	Fail- https://jam.dev/c/2d18958e-2346-4262-b992-8af444b9db31

**Comment by Ishankoradia** [comment]
This should be fix it - https://github.com/DalgoT4D/dbt-automation/pull/98 

Its released to staging, please test once @nairabhishek73

**Comment by nairabhishek73** [comment]
Hi still failing: https://jam.dev/c/9adb342e-125a-4d33-a929-5e09d14ab15e

**Comment by Ishankoradia** [comment]
@nairabhishek73 can we close this now ? On discord you tested and mentioned it works

**Comment by nairabhishek73** [comment]
Yes can close- but note arithmetic has not been tested thoroughly yet so things may pop up.
