### ISSUE TITLE
aggregate all fields to be marked as required and toast

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#671]
Blank save- Needs toast with notification, all fields to be marked as required

**Comment by fatchat** [comment]
no longer allows user to proceed without complete form
BUT
no indications e.g. toast / cell highlighting / helpful text etc

**Comment by fatchat** [comment]
#735

**Comment by Ishankoradia** [comment]
duplicate of #735

**Comment by fatchat** [comment]
![Image](https://github.com/DalgoT4D/webapp/assets/2160416/305d734e-d74e-4693-b15b-b176fd803e82)
