### ISSUE TITLE
Cast Bug

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#673]
Cast	Add one cast function after another-Current type and type options not showing	
https://jam.dev/c/bb0a4dbb-ef22-4003-a9ee-ddb0232baefd

This has happened thrice while testing

**Comment by fatchat** [comment]
since we are not carrying data types through the operations chain, we can't currently support casting after casting

@mdshamoon the operations
- cast
- table union
- flattenjson

can only be done at the beginning of an operations chain, could we remove them from the menu subsequently

**Comment by mdshamoon** [comment]
@fatchat @Ishankoradia I see a PR linked to this issue. Is this completed?

**Comment by nairabhishek73** [comment]
Fixed by adding a cue to create a table to add these functions.
