### ISSUE TITLE
Replace value with null and null with value doesnt work, should it?

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#679]
https://jam.dev/c/a2d3f663-43e2-47e9-b481-323a6f7762e2

**Comment by siddhant3030** [comment]
@nairabhishek73  replace shouldn;t be used to do this operations. For handling NULL values specifically, SQL provides mechanisms like COALESCE, IFNULL (in some SQL dialects like MySQL), or a CASE statement, which can be used to substitute NULL values with a specific value, such as 0.
```

SELECT COALESCE(NULLIF(column_name, ''), '0')::numeric
FROM table_name;
```
