### ISSUE TITLE
Change grid behavior

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/webapp#703]
The grid component currently adds a new cell when the left-hand cell of any row is modified

a. stop doing this
b. add new rows when either
b1. <Enter> is pressed in the right-hand cell of the last row
b2. The <+> button (to be introduced) is pressed

The <+> button will be below the grid, "+ Add row", same styling as "+ Add case n" in the CASE form

At most one empty row should exist in the grid
This empty row should be at the bottom of the grid

Each left-hand cell in the grid should have an "x" control to remove that row, positioned towards the right of the cell

**Comment by mdshamoon** [comment]
@fatchat can we do the x control at the last of the row. If we do it in the first column it doesnt seems intuitive if it will remove the autocomplete or the whole row

<img width="406" alt="Screenshot 2024-03-27 at 12 32 36 PM" src="https://github.com/DalgoT4D/webapp/assets/32592458/3c885700-7896-42b0-84ca-0ace473849d4">

**Comment by fatchat** [comment]
@mdshamoon yes all right
