### ISSUE TITLE
Trim column values feature

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/webapp#706]
Currently for atecf pipeline I want to do CAST change for one of the column from text to integer or numeric. But I'm not able to do it because the column value has some extra space which we need to trim before we I do text to numeric CAST type change

the error it will throw 
<img width="1322" alt="Screenshot 2024-03-26 at 12 45 29 AM" src="https://github.com/DalgoT4D/webapp/assets/9019958/3917ba7c-e853-4f0a-a424-b5f9f0577897">

The query I'm using 
```

SELECT COALESCE(NULLIF(TRIM(silt_target), '')::numeric, 0)
FROM production.rename_work_order;
```

**Comment by siddhant3030** [comment]
@nairabhishek73 look at this also

**Comment by nairabhishek73** [comment]
Yes discussed and will build this out in v2.1. Have share with vrushabh for designs by next week.
