### ISSUE TITLE
UI transform, Arithmetic: Error when I try to divide one column by another

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#709]
PID 953009 stream output: [0m03:30:36 [31mCompleted with 1 error and 0 warnings:[0m [0m03:30:36 [0m03:30:36 Database Error in model arithmetictable (models/intermediate/arithmetictable.sql) zero-length delimited identifier at or near """" LINE 18: ( "" ) / nullif( ( "TotalCases" ), 0) ^ compiled Code at target/run/dbtrepo/models/intermediate/arithmetictable.sql

Got this error. What does it mean?

**Comment by fatchat** [comment]
it means your fraction doesn't have a numerator... which looks like a bug somewhere. how did you set it up? i'll try to reproduce

**Comment by nairabhishek73** [comment]
I don't remember unfortunately, but i just did total tests by total cases and it worked so closing this for now. Will create an issue if it pops back up

**Comment by fatchat** [comment]
@Ishankoradia can you add validation to the arithmetic op form please

**Comment by fatchat** [comment]
covering as part of #735
