### ISSUE TITLE
Duplicate Table names in dropdowns

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#710]
Please display `schemaname.tablename` when there are duplicates

(union, join, ...?)

<img width="621" alt="Screenshot 2024-03-26 at 9 23 36 AM" src="https://github.com/DalgoT4D/webapp/assets/119285990/a51e1189-c933-47aa-89db-bb85f0312c7e">

**Comment by Kushdapush** [comment]
Hey @nairabhishek73
I would love to work on this issue if it's open for contributions!! 
Also I would like to know more about DalgoT4D. Could you please help me with this

**Comment by fatchat** [comment]
Hi @Kushdapush as discussed on Discord this issue isn't open for contributions, but please go look at the BQ form that's a good one

**Comment by nairabhishek73** [comment]
Also applicable to union.

**Comment by Ishankoradia** [comment]
![Image](https://github.com/DalgoT4D/webapp/assets/39583356/2b36ace1-cb70-481c-be16-45f174a8dc01)

we will try to do something like this 
`Schema1`
      - Table1
      - Table2
      - Table3
`Schema2`
    - Table 1 ....

**Comment by nairabhishek73** [comment]
Works
