### ISSUE TITLE
Total rows of a table in preview

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#714]
Before the latest release I was able to see total rows in a dataset. I think that's very helpful. Could we bring it back to the left of rows per page.

**Comment by nairabhishek73** [comment]
Additonally would be great if i could get some options for pagination row limits - like 5, 10, 50, 100, and allow users to scroll vertically.

**Comment by fatchat** [comment]
@nairabhishek73 rows-per-page can be selected with that little dropdown

<img width="271" alt="image" src="https://github.com/DalgoT4D/webapp/assets/2160416/ca73edb7-7bb9-408f-a940-ad71df8b63f9">



for total # rows, you want something like "1234 Rows; Rows per page: ..." ?

**Comment by nairabhishek73** [comment]
Oh missed that sorry.

Total rows: _________    Rows per page: _______

**Comment by mdshamoon** [comment]
@nairabhishek73 the total count is there which is a pretty standard UI for pagination. Let me know if we want to change it.
<img width="403" alt="image" src="https://github.com/DalgoT4D/webapp/assets/32592458/fa58c5e9-026d-4dfc-884d-3112517e0481">

**Comment by nairabhishek73** [comment]
Ah sorry shamoon and rohit. Missed this
