### ISSUE TITLE
UI Transform Info buttons

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#717]
Please check the following sheet: https://docs.google.com/spreadsheets/d/19PSe8ppA0V5AEwNOMC6fyprPu_96vQWsw8kU7uAfFFY/edit?usp=sharing

@fatchat @ashwinit4d 

Please make edits as you see fit, first in the sheet, then to the platform. Please notify regarding changes so I can go check.

**Comment by nairabhishek73** [comment]
Update:
Case- When:	Select the relevant column, operation, and comparison column or value.
Replace:	Replace all the row values in a column with a specified string with a new value

**Comment by fatchat** [comment]
for replace i'm making it "'Replace all the row values in a column having a specified string with a new value'

also some of them have a period `.` at the end i'm removing them for consistency

**Comment by fatchat** [comment]
![Image](https://github.com/DalgoT4D/webapp/assets/2160416/02f5f75b-142c-49eb-848f-a05cb6b4e5ae)



![Image](https://github.com/DalgoT4D/webapp/assets/2160416/1e8f83b6-e024-4aa9-9de6-0c4a4cda7a0a)
