### ISSUE TITLE
Sync sources is having an issue

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/webapp#730]
For this one I was facing an issue where column had empty values and I was not able to CAST it to numeric because of the issue which I've mentioned here 

https://github.com/DalgoT4D/webapp/issues/729 

So after I updated this at the database level to remove strings and add null values in the column the I was expecting I do the sync source again it will basically update the data but its not doing that and I'm not able to cast for which I'm  getting this issue and its not creating any table and I can't even check logs

<img width="1488" alt="Screenshot 2024-03-28 at 2 11 20 AM" src="https://github.com/DalgoT4D/webapp/assets/9019958/ee79f637-ce84-471c-a4da-30f5c871cccc">

So after this I've created a new org and added the same warehouse  to update the same table from different org which seems to work. 

@fatchat @Ishankoradia  we need to find a good solution for this. Happy to discuss more

**Comment by siddhant3030** [comment]
This is also stopping me to move forward from one set of flow. Now I'm stuck at this place 
@nairabhishek73  please look into this

**Comment by fatchat** [comment]
@siddhant3030 

sync-sources rescans for schemas and tables, not for changes to tables. so you didn't need to sync-sources and this issue is not related to it

to understand what is going on, you had a string column and made some values `null` is that correct?

did you delete and re-create the failing model?

**Comment by fatchat** [comment]
also if you would put all relevant org names into the issue descriptions it would let me investigate better

**Comment by siddhant3030** [comment]
> @siddhant3030
> 
> sync-sources rescans for schemas and tables, not for changes to tables. so you didn't need to sync-sources and this issue is not related to it
> 
> to understand what is going on, you had a string column and made some values `null` is that correct?
> 
> did you delete and re-create the failing model?

Yes. I had to delete it and create it again

**Comment by siddhant3030** [comment]
> > @siddhant3030
> > sync-sources rescans for schemas and tables, not for changes to tables. so you didn't need to sync-sources and this issue is not related to it
> > to understand what is going on, you had a string column and made some values `null` is that correct?
> > did you delete and re-create the failing model?
> 
> Yes. I had to delete it and create it again

Please look at this org new_test-4. this still have that failed table

**Comment by fatchat** [comment]
hi there is no `cast` model in this repo

<img width="554" alt="image" src="https://github.com/DalgoT4D/webapp/assets/2160416/b7343a77-da0b-4e59-b823-d7a4034c82fc">

for future reference, when reporting errors with operations please include the
- org name
- target schema
- model name

which will allow me to find the dbt code on disk for inspection

in cases where you are stuck before creation of the dbt model, please include the name of the operation which got stuck. in this case i'm assuming it is `cast_work_operation` ?

if the dbt run fails, please include the relevant log lines as well
