### ISSUE TITLE
tooltip for operations which start at the beginning of a chain

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#733]
https://jam.dev/c/0d6e7732-81e8-4f2e-b61a-759c93d828e6

**Comment by fatchat** [comment]
For the tooltips "Please create a table to use this function":

instead of the tooltip showing up on "hover-over-menuitem-text", it should show up on
- hover over row
- click on row

**Comment by nairabhishek73** [comment]
Tested and doesn't work. guessing this is yet to be pushed.
