### ISSUE TITLE
View operation configuration: lag and occassionallly non-responsive on click

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#738]
https://jam.dev/c/968fb6b8-f72d-43e7-936f-a98584d43572

**Comment by fatchat** [comment]
correct we can add a spinner while loading the configuration

**Comment by nairabhishek73** [comment]
Nothing to be done about the time taken to load? If not now then later? Is it possible to deal with?

**Comment by fatchat** [comment]
"about time taken to load" :  we won't make it faster we'll add a spinner

**Comment by nairabhishek73** [comment]
But can it be made faster at some point?
