### ISSUE TITLE
Edit Mid-Workflow

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#742]
Users should be able to edit mid workflow.

Edits can be of two types:
1. Altering the configuration of one or more existing function nodes mid workflow
2. Adding one or more function nodes in between existing nodes.

**To begin, we should allow altering configuration of existing nodes.** 

When a user edits mid-workflow this could have downstream effects of two types:
1. Errors: Ex. Drop an additional column in the middle which is referenced downstream.
2. Unexpected changes in models: Ex: Add x to a column in the middle, could have impact on percentage values downstream

Editing mid-workflow should address errors as follows:
1. Whenever an edit is made mid-stream and saved there should be an alert popup that says. "Editing functions may have have downstream effects in your workflow."  "Edit and run"  "Cancel"
2. Whenever a user edits mid workflow the workflow should run again and generate errors, if any.
3. We should also inform the user of which tables have changed as a result of this edit.
4. The user can then try to fix, else move ahead.

@ashwinit4d @fatchat @Ishankoradia @mdshamoon let me know what you think or if i've missed anything.

**Comment by fatchat** [comment]
@nairabhishek73 would you explain

`Adding one or more function nodes in between existing nodes.`

**Comment by nairabhishek73** [comment]
Adding one or more function in between existing nodes.
Assume TableX>FunctionA>TableY
I want to add Funcion B somehwere between Table X and Table Y

**Comment by fatchat** [comment]
@nairabhishek73 

(1) is done, (2) is not

i'm assuming they want to create a duplicate and then edit the nodes within the copy? what happens until they make those edits i.e. suppose they hit "run" do we run or do we say "please configure your new nodes"

we could run but it makes no sense (same table gets created twice)

if we insist on configuration, are we okay with only one change? or does every node need to change? or does only the name of the output table / schema change?

once we understand this could we open a new issue
