### ISSUE TITLE
Educate Beta account transform page error

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#746]
<img width="1470" alt="Screenshot 2024-04-04 at 8 29 17 AM" src="https://github.com/DalgoT4D/webapp/assets/119285990/5d4e5554-be2c-4565-9780-30d2d08e4838">

**Comment by fatchat** [comment]
There was no dbt-cli-profile block in prefect
I deleted the dbt workspace, opened the UI and selected the "UI" transformation type
Now it works

Prefect logs were full of closed connections to its database

Hypothesis: When they set it up, Prefect crapped out before completing the workspace setup

Solution: If an OrgDbt exists but the org has no dbt-cli-profile block, delete and re-create the workspace https://github.com/DalgoT4D/DDP_backend/issues/529

Close? @nairabhishek73

**Comment by fatchat** [comment]
fyi sync_sources isn't working for their workspace https://github.com/DalgoT4D/DDP_backend/issues/530

**Comment by fatchat** [comment]
`sync-sources` through an ssh tunnel will work once we release 
1. https://github.com/DalgoT4D/dbt-automation/pull/104
2. https://github.com/DalgoT4D/DDP_backend/pull/539

to `beta.dalgo.in`

running dbt will require
3. https://github.com/DalgoT4D/prefect-proxy/issues/110

which still has to be validated

**Comment by fatchat** [comment]
educate replaced the local postgres with a managed digital ocean postgres and were able to successfully to connect to it from dalgo

closing this issue
