### ISSUE TITLE
"Add a new..." => "Edit..." when editing a connection

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/webapp#753]
## Description
Dalgo connections have a single form for creation and updates, the mode is inferred by the props passed to the React component. We mistakenly use the same title for the form for both cases: "Add a new connection". This needs to be changed when the user is editing an existing connection

## Goals
- [ ] When editing an existing connection, the title should say "Edit this connection"

## Expected Outcome
This is a minor change to our edit-connection form

## Acceptance Criteria
- [ ] New connection setup should continue to have the title "Add a new connection"
- [ ] Existing connections being edited should have the title "Edit this connection"

## Implementation Details
This needs to be fixed in `CreateConnectionForm.tsx`

## Mockups / Wireframes
This is the current view which is wrong:
![image](https://github.com/DalgoT4D/webapp/assets/2160416/5286dc37-79ea-45a8-aa96-2726869540b8)

### Product Name
Dalgo

### Project Name
Dalgo

### Organization Name:
Project Tech4Dev

### Domain
30 Others

### Tech Skills Needed:
JavaScript, React

### Mentor(s)
@fatchat 

### Complexity
Low

### Category
Bug

### Sub Category
Frontend, Beginner friendly

**Comment by masterismail** [comment]
Hi @fatchat , can I work on this ?

**Comment by fatchat** [comment]
> Hi @fatchat , can I work on this ?

@masterismail please do! submit a PR i'll review it

**Comment by masterismail** [comment]
![image](https://github.com/DalgoT4D/webapp/assets/111173270/2621efca-835b-4e17-b36d-59b40c6ff443)

In order to test the implemented changes in a live environment, would I require a signup code?

**Comment by fatchat** [comment]
> ![image](https://private-user-images.githubusercontent.com/111173270/320364130-2621efca-835b-4e17-b36d-59b40c6ff443.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NTU1OTYsIm5iZiI6MTcxMjU1NTI5NiwicGF0aCI6Ii8xMTExNzMyNzAvMzIwMzY0MTMwLTI2MjFlZmNhLTgzNWItNGUxNy1iMzZkLTU5YjQwYzZmZjQ0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQwNTQ4MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNWE0YmZmMTk0ODlkZjkxYTk2YjliNmM5MTIzYzUzODRmN2FhNzJkNjgzYjkxNzI0NmUzYjRhYjQyMTg2NGFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vuacOm8danzILgU4BaRFsD8SEEyAiVfdgMJaAXN1yzM)
> 
> In order to test the implemented changes in a live environment, would I require a signup code?

@huzaifmalik786 can you help ismail connect to the staging account i gave you

**Comment by huzaifmalik786** [comment]
@masterismail , you can use these creds:
Username: huzaifmalik7860@gmail.com
Password: Huzaif@123

**Comment by fatchat** [comment]
@huzaifmalik786 don't put passwords here on github, use discord instead 
thanks
