### ISSUE TITLE
Add tooltips to Side Menu; add new icon for Usage Dashboard

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/webapp#758]
## Description
This issue will enhance the Dalgo side menu in two ways:
1. Add tooltips on mouse hover, saying what each menu item is
2. Replace the current icon for "Usage" with the new one

## Goals
- [ ] Add Tooltips for every menu item in `SideDrawer.tsx`
- [ ] Create a new `UsageIcon` in `assets/icons/`
- [ ] Replace the icon for `Usage in `menu.tsx` with the new `UsageIcon`

## Expected Outcome
The side menu's icon for Analysis->Usage should show the svg given below, and hovering over each menu item should show the name of the menu item, even when the side menu is minimized

## Acceptance Criteria
- [ ] Tooltips for every menu item in `SideDrawer.tsx`
- [ ] Tooltips visible when sidemenu is minimized
- [ ] New icon for Analysis->Usage

## Implementation Details
The svg to be used for the `UsageIcon` is
```
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M14 21C13.7348 21 13.4804 20.8946 13.2929 20.7071C13.1054 20.5196 13 20.2652 13 20V12C13 11.7348 13.1054 11.4804 13.2929 11.2929C13.4804 11.1054 13.7348 11 14 11H20C20.2652 11 20.5196 11.1054 20.7071 11.2929C20.8946 11.4804 21 11.7348 21 12V20C21 20.2652 20.8946 20.5196 20.7071 20.7071C20.5196 20.8946 20.2652 21 20 21H14ZM4 13C3.73478 13 3.48043 12.8946 3.29289 12.7071C3.10536 12.5196 3 12.2652 3 12V4C3 3.73478 3.10536 3.48043 3.29289 3.29289C3.48043 3.10536 3.73478 3 4 3H10C10.2652 3 10.5196 3.10536 10.7071 3.29289C10.8946 3.48043 11 3.73478 11 4V12C11 12.2652 10.8946 12.5196 10.7071 12.7071C10.5196 12.8946 10.2652 13 10 13H4ZM9.5 11.2929V4.5H4.5V11.2929H9.5ZM4 21C3.73478 21 3.48043 20.8946 3.29289 20.7071C3.10536 20.5196 3 20.2652 3 20V16C3 15.7348 3.10536 15.4804 3.29289 15.2929C3.48043 15.1054 3.73478 15 4 15H10C10.2652 15 10.5196 15.1054 10.7071 15.2929C10.8946 15.4804 11 15.7348 11 16V20C11 20.2652 10.8946 20.5196 10.7071 20.7071C10.5196 20.8946 10.2652 21 10 21H4ZM4.5 19.5H9.5V16.5H4.5V19.5ZM14.5 19.5H19.5V12.5H14.5V19.5ZM13 4C13 3.73478 13.1054 3.48043 13.2929 3.29289C13.4804 3.10536 13.7348 3 14 3H20C20.2652 3 20.5196 3.10536 20.7071 3.29289C20.8946 3.48043 21 3.73478 21 4V8C21 8.26522 20.8946 8.51957 20.7071 8.70711C20.5196 8.89464 20.2652 9 20 9H14C13.7348 9 13.4804 8.89464 13.2929 8.70711C13.1054 8.51957 13 8.26522 13 8V4ZM14.5 4.5V7.5H19.5V4.5H14.5Z" fill="#7D8998"/>
</svg>
```

### Product Name
Dalgo

### Project Name
Dalgo

### Organization Name:
Project Tech4Dev

### Domain
30 Others

### Tech Skills Needed:
JavaScript, React

### Mentor(s)
@fatchat 

### Complexity
Low

### Category
Feature

### Sub Category
Frontend, Beginner friendly

**Comment by Kushdapush** [comment]
Hey @fatchat , I would like to work on this issue!

**Comment by fatchat** [comment]
Go for it!

**Comment by SanjanaSogimatt** [comment]
@fatchat Can I work on this too?

**Comment by Kushdapush** [comment]
hey @SanjanaSogimatt  @fatchat , i have nearly completed the issue!! , if needed i will surely reach out to you for help in the mean  time you can find more similar Issues at  https://www.codeforgovtech.in/community-program-projects

Also this is a very small UI enhancement and not suitable for multiple people to work at the same time !!

**Comment by Kushdapush** [comment]
@fatchat PTAL
