### ISSUE TITLE
add NULL to column / value selection

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/webapp#772]

**Comment by Venki1402** [comment]
Hey @fatchat,
I want to contribute here but I'm not clear about the issue based on the title so could you please provide more details on this issue?

**Comment by fatchat** [comment]
hi @Venki1402 this was meant to be an internal issue. i'll tag it "c4gt community" if i want external contributions, thank you

**Comment by Venki1402** [comment]
Alright, Thank you.
