### ISSUE TITLE
Fix overflowing elements when drawer is collapsed

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/webapp#794]
## Description
On some web browsers, the sidemenu elements are still clickable even when the sidemenu is collapsed

## Goals
- [ ] Fix this

## Expected Outcome
This should no longer occur 

## Acceptance Criteria
- [ ] The carets should not appear in the main page
- [ ] The documentation link should not be clickable when it's not even visible

### Product Name
Dalgo

### Project Name
Dalgo

### Organization Name:
Project Tech4Dev

### Domain
30 Others

### Tech Skills Needed:
JavaScript, React

### Mentor(s)
@fatchat 

### Complexity
Low

### Category
Bug

### Sub Category
Frontend

**Comment by soumya-maheshwari** [comment]
Hi @fatchat 
is this issue still opened
if it is i would like to work on it.

**Comment by Abhi-0001** [comment]
Hello @fatchat I have been finding issues on react. Can I work on it if it is not closed yet?

**Comment by Utsavladia** [comment]
Hello @fatchat,

I've reviewed the issue and I'm eager to contribute. With my experience in React, I'm confident I'm the best fit for the task. If given the chance, I'll apply my full interest and perform exceptionally well. Looking forward to the opportunity.
