### ISSUE TITLE
Lower pane to become expandable to full window

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#798]
Currently the preview and logs pane can be dragged up or down to change its size.
Request from Inrem and Goalkeep to make this expandable to full screen.

Given that Data Statistics is enabling this the request is for us to have the expand button on the right as in Vrushabh's figma designs for the same. This will expand the entire window, following which you can toggle between logs, preview, and data statistics.

**Comment by fatchat** [comment]
@mdshamoon would you need a design or is it clear
