### ISSUE TITLE
Warehouse destination icon not getting rendered after upgrade to Airbyte 0.50.44

### ISSUE THREAD

**Issue by Snehil-Shah** [DalgoT4D/webapp#812]
**Describe the bug**

![image](https://github.com/DalgoT4D/webapp/assets/130062020/f467764a-addb-45be-9c10-01d4ef83253b)

The URL to the `svg` is printed instead of rendering the icon.

Relevant part of code:

![image](https://github.com/DalgoT4D/webapp/assets/130062020/c4ed4270-34b3-43cd-b8e5-8c90c5eef023)

**To Reproduce**
1. Go to Ingest>Your warehouse
2. Click on Create destination and create a postgres sink
3. See error

**I am not sure if this is a problem specific to my setup or not, so would appreciate confirmation..**

If this bug is confirmed, I would like to work on fixing it...

**Expected behavior**
The icon should be rendered.

**Desktop (please complete the following information):**
 - OS - Browser on windows, setup on linux with ports forwarded to the windows machine
 - Browser - Chrome
 - Chrome Version 124.0.6367.61 (Official Build) (64-bit)

**Additional Context**
Yes the `SVG` resource link is working:

![image](https://github.com/DalgoT4D/webapp/assets/130062020/1d5029e2-81b5-4d30-934b-424f6b3da220)

**Comment by fatchat** [comment]
yes this is a known issue... our code is correct for the version of airbyte running on production, but not for the version running on staging. we will fix it just before the upgrade

**Comment by Pratik-050** [comment]
Hello @fatchat I've made some changes to display the icon instead of the link. Is it still open or someone is working on this?
