### ISSUE TITLE
Syncing sources on Ui transform

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#835]
https://jam.dev/c/b10c8d31-0b8c-44a5-8217-a85607cd9d9c

Taking too long

Ui testing org 6 on staging

If I leave the screen and come back it seems the sync is restarting(based on the logs). Shouldn't it have continued?

**Comment by fatchat** [comment]
https://github.com/DalgoT4D/DDP_backend/pull/583

**Comment by fatchat** [comment]
@nairabhishek73 is this still happening? sync-sources was enhanced to 
- detect and report failures
- report progress
- unlock after a few minutes in case of unhandled errors
