### ISSUE TITLE
streams appear unsorted when creating a connection

### ISSUE THREAD

**Issue by jakejh** [DalgoT4D/webapp#839]
<img width="869" alt="Screenshot 2024-04-23 at 07 45 25" src="https://github.com/DalgoT4D/DDP_backend/assets/2295314/6b81f857-7ffe-475d-9dd0-21c83509d031">

**Comment by fatchat** [comment]
https://github.com/DalgoT4D/webapp/issues/840

**Comment by Abhi-0001** [comment]
Hello @jakejh I want to contribute to this ticket. Can you please elaborate the sorting of items that which criteria should be followed for sorting?

**Comment by fatchat** [comment]
@Abhi-0001 please only work on tickets which have been tagged "C4GT Community" thanks
