### ISSUE TITLE
Sort streams by name in the Connections form

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/webapp#840]
## Description
Dalgo's Connections form shows a list of streams for that connection. The list is currently not sorted by name

## Goals
- [ ] Sort this list alphabetically by name

## Expected Outcome
The connections form (new / edit) should show streams sorted alphabetically by name

## Acceptance Criteria
- [ ] The connections form (new / edit) should show streams sorted alphabetically by name
- [ ] Jest tests should be updated as required

## Implementation Details
Start at `CreateConnectionForm.tsx`

## Mockups / Wireframes
This is the current view

![image](https://github.com/DalgoT4D/webapp/assets/2160416/396f62f6-f770-4ee4-b8ac-25f98bbbcbcc)

### Product Name
Dalgo

### Project Name
Dalgo

### Organization Name:
Project Tech4Dev

### Domain
30 Others

### Tech Skills Needed:
React

### Mentor(s)
@fatchat 

### Complexity
Low

### Category
UI/UX/Design

### Sub Category
Frontend, Beginner friendly

**Comment by Harine19** [comment]
I am currently working on this issue as soon as you posted it, can you assign it to me?

**Comment by Harine19** [comment]
I have it running and will resolve the issue soon 
![Screenshot (44)](https://github.com/DalgoT4D/webapp/assets/99670243/84e4154d-f75f-491f-ab1e-ae890b292b69)

**Comment by Akshat-Jaiswal-8** [comment]
hey @fatchat , i've made the changes and raised a PR. But in my local I'm able to see only one source stream.
![image](https://github.com/DalgoT4D/webapp/assets/134438167/1f065cb2-e344-45fb-bf99-186d2cc8586b)

But the changes i've made will probably work . If found any inconsistency , i'll make the changes.

**Comment by Harine19** [comment]
@fatchat As mentioned before, I've completed resolving the issue. 
I have sorted the streams alphabetically and all the streams are present. 
I have also added the corresponding test. With having to make both changes it took a while, but I have finished it and raised a PR, the automatic tests you've set have also ran successfully, 

Please do review, thanks!
