### ISSUE TITLE
RBAC: switch user role

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#877]
https://jam.dev/c/70139b1a-fa1e-4cad-a4c8-b25c6e74c481

**Comment by fatchat** [comment]
The video shows the actions menu sometimes visible and sometimes not

**Comment by nairabhishek73** [comment]
https://jam.dev/c/df48174a-ef84-4f5a-baaa-f894db255bc5

So when I enter the user management screen these options aren't showing. When I click away and come back they show.
When i tried reloading (not in the video) it didnt show the options
@mdshamoon
