### ISSUE TITLE
RBAC- Account manager deletion and role changing permissiions bug

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#881]
New account manager cannot delete old account manager- says cannot delete user of higher role. They are at the same role and this should be possible. Consider org transitions

New account manager cannot change old account manager's role- says sucessful but is actually not resulting in anything.
https://jam.dev/c/9a438f8d-dbf3-4786-92f9-3ffd2131a307

**Comment by fatchat** [comment]
so weird the backend code which generates the message `cannot delete user of higher role` does the correct check i.e. a strict inequality

`orguserfunctions.delete_orguser_v1`

<img width="516" alt="image" src="https://github.com/DalgoT4D/webapp/assets/2160416/e06257d3-71b7-4072-b663-65fa64eb3e41">

tell me the org name and the email addresses of the two account managers? @nairabhishek73

**Comment by nairabhishek73** [comment]
New account manager is able to change old account manager role. But new account manager still cannot dele old account manager.

https://jam.dev/c/69e2a108-4a08-4ed4-9637-eec861b61228

**Comment by nairabhishek73** [comment]
Okay now resolved. Thanks @mdshamoon
