### ISSUE TITLE
Schema Change Detection 2: Sticky indicator at the top of connection page with connection detail under pending changes

### ISSUE THREAD

**Issue by Abhishek-N** [DalgoT4D/webapp#901]

**Comment by Abhishek-N** [comment]
Once a mail is sent at night if there is a schema change in a connection for an org, it should also save the details of the same in a table. This is done because we don't have to connect to source everytime in the connections page which takes time to load

- [ ] Create a `SchemaChange` table that saves connection_id, org, schema_change (type)
- [ ] Update the celery task to save these details in the table(add, update and delete row) by connection_id
- [ ] connection_id should be unique in this table so that if the user manually checks for schema change it won't add a new row in the table
- [ ] Write an api to fetch data from this table specific to org
- [ ] In the connections page, we check from this api for schemaChange and if there is a schemaChange display connection and breaking change type in pending actions tab

**Comment by fatchat** [comment]
the `SchemaChange` table should not only contain the schema_change type, it should contain the details of the changes i.e. enough for you to show the user in the UI

**Comment by Abhishek-N** [comment]
PR: #904
