### ISSUE TITLE
Minimise left pane- enable a view of the entire width of the elementary pane

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#926]
**Is your feature request related to a problem? Please describe.**

Need to scroll right often to view more information on elementary

**Describe the solution you'd like**
Enable the entire width of the screen to be visible, by first enabling a minimisation of the left menu pane and second fit to screen the elementary embedded view

**Comment by fatchat** [comment]
The side menu is already minimizable
