### ISSUE TITLE
If all values are distinct there should be no mode

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#946]
https://jam.dev/c/a98920ad-509f-4f61-a4d5-ea0c0ad6d3b1

If all dfistinct values or if more than one value is repeated most times then don't show mode or show mode as NA

**Comment by Ishankoradia** [comment]
@mdshamoon i have made the change. If all values are distinct, mode will be `null`.

**Comment by mdshamoon** [comment]
This is fixed. @nairabhishek73 ready for testing
