### ISSUE TITLE
String length distribution when all values are the same- overlap

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#949]
https://jam.dev/c/fced25f1-e0fd-4e23-a7ad-4cd22be2a232

Should also consider this case for numeric. For numeric at least there is another visual option. For string length distribution there isn't.

**Comment by mdshamoon** [comment]
This is fixed. Ready for testing.
Added a check if min and max values are equal than show text `All column values are equal in length` in case of string and ` `All column values are equal` in case of integer
