### ISSUE TITLE
Date-time visuals are glitching

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#950]
https://jam.dev/c/eb6d69c3-4264-42f5-8ed2-51515789bc2b

Flickering of screen
Graph shows correctly, then glitches and then none of the drill down graphs show. i think the problem is with the option to move left and right to view the spectrum of time not immediately captured in the graph.

Beta- Demo Acc

**Comment by nairabhishek73** [comment]
https://jam.dev/c/40e362d5-d06e-405c-8a69-3435e02a643f

**Comment by mdshamoon** [comment]
Hey @Ishankoradia please check this one. Seems to be some data issue

**Comment by Ishankoradia** [comment]
This is fixed. @nairabhishek73
