### ISSUE TITLE
Block connection sync if the connection is involved in a pipeline that is running. Indicate that it is being synced.

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#955]
https://jam.dev/c/e6b48996-2930-4085-9e72-08eb3a1eacb7

**Comment by himanshudube97** [comment]
-> Is the issue already resolved? I ran the sync in **orchestrate** and it is showing the same in **ingest** too.
![Screenshot 2024-07-07 212241](https://github.com/DalgoT4D/webapp/assets/114103742/41c0d2b4-5d2e-49ff-bb82-11b22b557e40)
![Screenshot 2024-07-07 212230](https://github.com/DalgoT4D/webapp/assets/114103742/a852be35-1028-4bf2-ab26-907909e6fbc7)

**Comment by fatchat** [comment]
well.. yes it was designed to do this, but somehow nair found it failing last month

you can take the opportunity to read the backend code to see our locking logic, maybe you will notice a bug

**Comment by fatchat** [comment]
but jest is still higher priority, that's why this is not for this week on the project schedule

**Comment by himanshudube97** [comment]
ok sir. got it. Thanks.

**Comment by Ishankoradia** [comment]
This is working as expected

**Comment by fatchat** [comment]
@nairabhishek73 are you still able to reproduce

**Comment by nairabhishek73** [comment]
Working as expected thanks
