### ISSUE TITLE
Schema change: Notification for 'no changes detected'

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#956]
https://jam.dev/c/44601da9-7b1c-4bd3-92ab-dbcd05ced348

Columns was added with no values in it

**Comment by fatchat** [comment]
the error toast at the beginning of the video should be fixed now can you retry

if you added an empty column to a google sheet i don't know whether or not airbyte detects it as a schema change.. i but i can make sure that we are reporting whatever airbyte reports
