### ISSUE TITLE
New column added to gsheet, sync run, no update

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#957]
https://jam.dev/c/169c860a-99d8-48c0-9aad-571865988bd2

sync via connections page and sync via orchestrate

**Comment by nairabhishek73** [comment]
This applies for all types of changes

**Comment by fatchat** [comment]
correct, running a sync does not refresh the schema. the schema is refreshed in one of two ways:
- via the nightly job
- by the user refreshing via the actions menu

**Comment by nairabhishek73** [comment]
Why is it setup to not refresh with every sync?

**Comment by fatchat** [comment]
Adding a refresh just makes the job longer, the refresh is done every night and can be triggered manually. Didn't see a need to add another trigger for refresh
