### ISSUE TITLE
Data Statistics: Column with all unique rows 100% in 'other'  is misguiding 

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#958]
https://jam.dev/c/7390503f-e003-4b9a-91fd-ae47326c5b93

Also the button location to togggle visuals should be consistent. Notice how it shifts in the view with the text.

**Comment by fatchat** [comment]
what would you like to show instead

**Comment by mdshamoon** [comment]
I think we can do the same thing we are doing for nulls. Just mentioning that `All values are distinct`
