### ISSUE TITLE
When a column is full of nulls it is showing no graph and if read as string then saying all  values are of the same length

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#960]
https://jam.dev/c/8760a0ee-fa16-4d91-a47a-b418cd3b6678

Should just indicate all values are null or "No Data Avaialable"

**Comment by Ishankoradia** [comment]
For string column
@mdshamoon  for this can we put a check if `totalCount == countNull` then we can change the wording of the statement to `....all values are null....`.

**Comment by mdshamoon** [comment]
This is fixed. @nairabhishek73 ready for testing
