### ISSUE TITLE
elementary feedback

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/webapp#967]
@Abhishek-N  Can we hide our side menu to see the elementary dashboard properly. Right now I'm not able to scroll down to see certain information and I have to zoom out to see the test cases. 

https://jam.dev/c/9d2b4e59-9fe2-4dda-9dff-5d0553ad4815

**Comment by fatchat** [comment]
@mdshamoon could we put the "regenerate" button and the "last generated at" text on the same line?

**Comment by siddhant3030** [comment]
> Hi yes we can. I had the same question and had raised an issue earlier. Lesser known feature :D
> 
> 1. Hit the three lines on the top left in Dalgo to minimise the menu.
> 2. Hit the second icon in elementary at the top left to minimise the elementary menu.
> 3. Now you should be able to see everything decently well
> 
> Agree though on inconvenient visibility. Imo when I zoom out to 80% it becomes ideal.
> 
> cc: @fatchat

<img width="1508" alt="Screenshot 2024-06-24 at 2 32 09 PM" src="https://github.com/DalgoT4D/webapp/assets/9019958/2601ce67-080d-4e90-82c8-7ef9b6456bbd">
Oh I didn't know that we can minimize this. This works for me actually
