### ISSUE TITLE
Added a new row, yet it says no records synced, no bytes synced

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#970]
https://jam.dev/c/0be40176-343e-448d-9e58-b84b818b86dc

**Comment by fatchat** [comment]
https://github.com/airbytehq/airbyte/issues/15333

**Comment by fatchat** [comment]
fixed; checked ui-testing-6 on staging, and on production arghyam, stir, kef, sneha

**Comment by fatchat** [comment]
@nairabhishek73 

![Image](https://github.com/DalgoT4D/webapp/assets/2160416/7bc2a7b5-7ecd-4ffa-a24d-5136fd9f5d79)

**Comment by nairabhishek73** [comment]
Hi works!
