### ISSUE TITLE
connection history is timing out

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/webapp#975]
1. when airbyte doesn't respond to `attempt/get_for_job` from `/api/airbyte/v1/connections/{conn_id}/sync/history` we should report back to the frontend and stop the spinner

2. even if we can't get the logs, can we get the other stats

3. and can we cache the other stats in a django table for future requests

**Comment by fatchat** [comment]
get logs directly from airbyte log folder
write up a spec in a google doc

**Comment by mdshamoon** [comment]
Now loading a log for a single connection separately in #1008. Should work fine for most cases.

**Comment by mdshamoon** [comment]
Tested on Noora Health. Working fine now.
