### ISSUE TITLE
schema changes should clarify tablenames vs columnnames

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/webapp#976]
when a connection has schema changes we show the user a popup which looks like this:

![Image](https://github.com/DalgoT4D/webapp/assets/2160416/71bd9e3a-3863-498f-95d0-0281e1f0644b)

in this screenshot there are two columns, the left one contains the names of the tables and the right one the names of the columns within that respective table

but the UI doesn't make this clear, making it confusing for the user

Please put in headers / some other visual aid to clarify this to the user

**Comment by fatchat** [comment]
see `SchemaChangeDetailsForm.tsx`

**Comment by himanshudube97** [comment]
![Screenshot 2024-07-02 135718](https://github.com/DalgoT4D/webapp/assets/114103742/b0a34e4e-fef3-4704-90a8-c70045adb3bf)

**Comment by fatchat** [comment]
I like it, would you get Shamoon's opinion as well please

**Comment by himanshudube97** [comment]
ok sir, i ll do that.
